# This file is automatically generated by RHIDE 1.5
# created with the command:
# gpr2mak easydiag.gpr
vpath_src=../easydiag
vpath %.c $(vpath_src)
vpath %.cc $(vpath_src)
vpath %.cpp $(vpath_src)
vpath %.C $(vpath_src)
vpath %.cxx $(vpath_src)
vpath %.s $(vpath_src)
vpath %.S $(vpath_src)
vpath %.p $(vpath_src)
vpath %.pas $(vpath_src)
vpath %.f $(vpath_src)
vpath %.for $(vpath_src)
vpath %.F $(vpath_src)
vpath %.fpp $(vpath_src)
vpath %.i $(vpath_src)
vpath %.ii $(vpath_src)
vpath %.m $(vpath_src)
vpath %.asm $(vpath_src)
vpath %.nsm $(vpath_src)
vpath_header=../easydiag $(TVISION_INC) ../settvuti/include
vpath %.h $(vpath_header)
vpath %.hpp $(vpath_header)
vpath %.ha $(vpath_header)
vpath %.hd $(vpath_header)
vpath_obj=obj
vpath %.o $(vpath_obj)
FLAGS_FOR_SUBPROJECTS=RHIDE_OS_="$(RHIDE_OS_)" CFLAGS="$(CFLAGS)"\
	CXXFLAGS="$(CXXFLAGS)" LDFLAGS="$(LDFLAGS)" CPPFLAGS="$(CPPFLAGS)"
RHIDE_OS=$(RHIDE_OS_)
ifeq ($(strip $(RHIDE_OS)),)
ifneq ($(strip $(DJDIR)),)
RHIDE_OS_:=DJGPP
else
RHIDE_OS_:=$(patsubst CYGWIN%,CYGWIN,$(shell uname))
endif
endif

INCLUDE_DIRS=../easydiag $(TVISION_INC) ../settvuti/include
LIB_DIRS=
C_DEBUG_FLAGS=
C_OPT_FLAGS=
C_WARN_FLAGS=
C_C_LANG_FLAGS=
C_CXX_LANG_FLAGS=
C_P_LANG_FLAGS=
C_FPC_LANG_FLAGS=
C_F_LANG_FLAGS=
C_ADA_LANG_FLAGS=
LIBS=tv intl
LD_EXTRA_FLAGS=
C_EXTRA_FLAGS=
LOCAL_OPT=$(subst ___~~~___, ,$(subst $(notdir $<)___,,$(filter $(notdir\
	$<)___%,$(LOCAL_OPTIONS))))

OBJFILES=obj/lablchek.o obj/lablradi.o obj/snostate.o obj/tcheck2.o\
	obj/tmiclust.o obj/tsbutton.o obj/tschkarr.o obj/tschkbox.o\
	obj/tshscrol.o obj/tshzgrp.o obj/tsinplin.o obj/tsinplpi.o\
	obj/tslabel.o obj/tslider.o obj/tslistbo.o obj/tsradbot.o\
	obj/tssortlb.o obj/tssosslb.o obj/tstatext.o obj/tstextsc.o\
	obj/tstsorlb.o obj/tsvegrp.o obj/tsview.o obj/tsviewco.o\
	obj/ttextscr.o
ALL_OBJFILES=obj/lablchek.o obj/lablradi.o obj/snostate.o obj/tcheck2.o\
	obj/tmiclust.o obj/tsbutton.o obj/tschkarr.o obj/tschkbox.o\
	obj/tshscrol.o obj/tshzgrp.o obj/tsinplin.o obj/tsinplpi.o\
	obj/tslabel.o obj/tslider.o obj/tslistbo.o obj/tsradbot.o\
	obj/tssortlb.o obj/tssosslb.o obj/tstatext.o obj/tstextsc.o\
	obj/tstsorlb.o obj/tsvegrp.o obj/tsview.o obj/tsviewco.o\
	obj/ttextscr.o
LIBRARIES=
SOURCE_NAME=$<
OUTFILE=$@
SPECIAL_CFLAGS=
SPECIAL_LDFLAGS=
PROG_ARGS=
SRC_DIRS=../easydiag
WUC=
EDITORS=
MAIN_TARGET=libeasyd.a
PROJECT_ITEMS=lablchek.cc lablradi.cc snostate.cc tcheck2.cc tmiclust.cc\
	tsbutton.cc tschkarr.cc tschkbox.cc tshscrol.cc tshzgrp.cc\
	tsinplin.cc tsinplpi.cc tslabel.cc tslider.cc tslistbo.cc\
	tsradbot.cc tssortlb.cc tssosslb.cc tstatext.cc tstextsc.cc\
	tstsorlb.cc tsvegrp.cc tsview.cc tsviewco.cc ttextscr.cc
DEFAULT_MASK=*.[acfghimnops]*
RHIDE_BIN_DIR=/usr/local/bin
PASCAL_TYPE=GPC
GET_HOME=$(HOME)
CLEAN_FILES=$(MAIN_TARGET) $(OBJFILES)
DEFAULT_GREP_MASK=*.[cfhmnps]*
RHIDE_ADA_BIND_FILE=$(addprefix _,$(setsuffix .c,$(OUTFILE)))
RHIDE_AR=ar
RHIDE_ARFLAGS=rcs
RHIDE_AS=$(RHIDE_GCC)
RHIDE_CO=$(shell co -q $(co_arg))
RHIDE_COMPILE.C.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.C.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.C.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.F.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.adb.o=$(RHIDE_COMPILE_ADA)
RHIDE_COMPILE.asm.o=$(RHIDE_COMPILE.nsm.o)
RHIDE_COMPILE.c.i=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.c.o=$(RHIDE_COMPILE_C)
RHIDE_COMPILE.c.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.cc.ii=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cc.o=$(RHIDE_COMPILE_CC)
RHIDE_COMPILE.cc.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cpp.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cpp.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cpp.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.cxx.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cxx.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cxx.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.f.o=$(RHIDE_COMPILE_FORTRAN)
RHIDE_COMPILE.for.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.fpp.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.i.s=$(RHIDE_COMPILE.c.s)
RHIDE_COMPILE.ii.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.nsm.o=$(RHIDE_COMPILE_NASM)
RHIDE_COMPILE.p.o=$(RHIDE_COMPILE_PASCAL)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pas.s=$(RHIDE_COMPILE.pas.s.$(PASCAL_TYPE))
RHIDE_COMPILE.pas.s.FPC=$(RHIDE_COMPILE_FPC) -a -s
RHIDE_COMPILE.pas.s.GPC=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_GPC))
RHIDE_COMPILE.pp.o=$(RHIDE_COMPILE_FPC)
RHIDE_COMPILE.s.o=$(RHIDE_COMPILE_ASM)
RHIDE_COMPILE_ADA=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  $(C_ADA_LANG_FLAGS)  $(RHIDE_OS_CFLAGS) $(CPPFLAGS)\
	$(CFLAGS) -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ARCHIVE=$(RHIDE_AR) $(RHIDE_ARFLAGS) $(OUTFILE)\
	$(ALL_OBJFILES)
RHIDE_COMPILE_ASM=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ASM_FORCE=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) -x assembler\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_C=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(RHIDE_OS_CFLAGS)  $(CPPFLAGS) $(CFLAGS) $(LOCAL_OPT) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_CC=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(RHIDE_OS_CXXFLAGS)\
	$(CPPFLAGS) $(CXXFLAGS) $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_CC_FORCE=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(RHIDE_OS_CXXFLAGS)\
	$(CPPFLAGS) $(CXXFLAGS) -x c++ $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_C_FORCE=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x c $(RHIDE_OS_CFLAGS)  $(CPPFLAGS) $(CFLAGS) $(LOCAL_OPT) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN_FORCE=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x f77 $(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FPC=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -E- $(SOURCE_NAME)
RHIDE_COMPILE_FPC_FORCE=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -B -E-\
	$(SOURCE_NAME)
RHIDE_COMPILE_GPC=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_GPC_FORCE=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) -x pascal\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_ADA=gnatbl $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(setsuffix .ali,$(OUTFILE)) $(LIBRARIES) $(LDFLAGS) \
	$(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_ADA_BIND=$(RHIDE_GNATBIND) -o $(RHIDE_ADA_BIND_FILE)\
	$(setsuffix .ali,$(OUTFILE))
RHIDE_COMPILE_LINK_ADA_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(RHIDE_ADA_BIND_FILE) $(OBJFILES) $(LIBRARIES)\
	$(LDFLAGS)  $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_DLL=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)  \
	$(RHIDE_SHARED_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_FPC=echo 'separate linking for FPK is not supported.\
	Please define a main source file in Project/Primary file.' 1>&2
RHIDE_COMPILE_LINK_FPC_AUTOMAKE=$(RHIDE_FPC) -o$(OUTFILE) $(SOURCE_NAME)\
	$(RHIDE_FPC_FLAGS) -E+
RHIDE_COMPILE_LINK_GPC=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS)\
	-o $(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(RHIDE_LDFLAGS) $(LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_GPC_AUTOMAKE=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS)  -o\
	$(OUTFILE) --automake $(RHIDE_GPC_FLAGS)  $(SOURCE_NAME)\
	$(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_PASCAL=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE))
RHIDE_COMPILE_LINK_PASCAL_AUTOMAKE=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE)_AUTOMAKE)
RHIDE_COMPILE_NASM=$(RHIDE_NASM) -f $(RHIDE_NASM_TARGET) $(LOCAL_OPT) -o\
	$(OUTFILE)  $(SOURCE_NAME)
RHIDE_COMPILE_PASCAL=$(RHIDE_COMPILE_$(PASCAL_TYPE))
RHIDE_COMPILE_PASCAL_FORCE=$(RHIDE_COMPILE_$(PASCAL_TYPE)_FORCE)
RHIDE_CONFIG_DIRS=. $(RHIDE_SHARE) $(GET_HOME)   $(RHIDE_CONFIG_DIRS_COMMON)\
	 $(addsuffix /SET,$(RHIDE_CONFIG_DIRS_COMMON))  $(SET_FILES)
RHIDE_CONFIG_DIRS_$(RHIDE_OS)=/usr/local/share/rhide /usr/share/rhide \
	/local/share/rhide /share/rhide
RHIDE_CONFIG_DIRS_COMMON=$(RHIDE_CONFIG_DIRS_$(RHIDE_OS))\
	$(RHIDE_BIN_DIR)/../share/rhide
RHIDE_CONFIG_DIRS_DJGPP=$(DJDIR)/share/rhide
RHIDE_CONFIG_DIRS_Linux=/usr/local/share/rhide /usr/share/rhide \
	/local/share/rhide /share/rhide
RHIDE_EMPTY=
RHIDE_FPC=ppc386
RHIDE_FPC_FLAGS=$(C_FPC_LANG_FLAGS) $(LOCAL_OPT) $(addprefix\
	-Up,$(INCLUDE_DIRS))  $(C_EXTRA_FLAGS)
RHIDE_FPC_LIBDIRS=$(RHIDE_FPC_LIBDIRS_$(RHIDE_OS))
RHIDE_FPC_LIBDIRS_$(RHIDE_OS)=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LIBDIRS_DJGPP=$(DJDIR)/lib
RHIDE_FPC_LIBDIRS_Linux=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LINK_FLAGS=$(RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS))
RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS)=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_DJGPP=-O coff-go32-exe $(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_Linux=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FSDB=fsdb $(OUTFILE) $(addprefix -p ,$(SRC_DIRS)) $(PROG_ARGS)
RHIDE_G77=g77
RHIDE_GCC=gcc
RHIDE_GDB=gdb $(OUTFILE) $(addprefix -d ,$(SRC_DIRS))
RHIDE_GNATBIND=gnatbind
RHIDE_GPC=gpc
RHIDE_GPC_FLAGS=$(RHIDE_INCLUDES) $(C_DEBUG_FLAGS) $(C_OPT_FLAGS)\
	$(C_WARN_FLAGS)  $(C_P_LANG_FLAGS) $(C_EXTRA_FLAGS)
RHIDE_GPROF=gprof $(OUTFILE)
RHIDE_GREP=grep -n $(prompt arguments for GREP,$(WUC) $(DEFAULT_GREP_MASK))
RHIDE_GXX=$(RHIDE_GCC)
RHIDE_INCLUDES=$(SPECIAL_CFLAGS) $(addprefix -I,$(INCLUDE_DIRS))
RHIDE_LD=$(RHIDE_GCC)
RHIDE_LDFLAGS=$(SPECIAL_LDFLAGS) $(addprefix -Xlinker ,$(LD_EXTRA_FLAGS))
RHIDE_LD_FPC=$(RHIDE_FPC) -E+
RHIDE_LD_PASCAL=gpc
RHIDE_LIBDIRS=$(addprefix -L,$(LIB_DIRS))
RHIDE_LIBS=$(addprefix -l,$(LIBS) $(RHIDE_TYPED_LIBS) $(RHIDE_OS_LIBS))
RHIDE_NASM=nasm
RHIDE_NASM_TARGET=$(RHIDE_NASM_TARGET_$(RHIDE_OS))
RHIDE_NASM_TARGET_DJGPP=coff
RHIDE_NASM_TARGET_Linux=elf
RHIDE_PATH_SEPARATOR=$(RHIDE_PATH_SEPARATOR_$(RHIDE_OS))
RHIDE_PATH_SEPARATOR_$(RHIDE_OS)=:
RHIDE_PATH_SEPARATOR_DJGPP=;
RHIDE_PATH_SEPARATOR_Linux=:
RHIDE_RLOG=$(shell rlog -R $(rlog_arg))
RHIDE_RM=rm
RHIDE_SHARED_LDFLAGS=$(RHIDE_SHARED_LDFLAGS_$(RHIDE_OS))
RHIDE_SHARED_LDFLAGS_$(RHIDE_OS)=
RHIDE_SHARED_LDFLAGS_Linux=-shared
RHIDE_SHARED_LDFLAGS_Linux=
RHIDE_SPACE=$(RHIDE_EMPTY) $(RHIDE_EMPTY)
RHIDE_STANDARD_INCLUDES=$(RHIDE_STANDARD_INCLUDES_$(RHIDE_OS))
RHIDE_STANDARD_INCLUDES_$(RHIDE_OS)=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_STANDARD_INCLUDES_DJGPP=$(addprefix $(DJDIR)/,include include/sys\
	lang/cxx lang/cxx/std)
RHIDE_STANDARD_INCLUDES_Linux=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_TYPED_LIBS=$(foreach\
	suff,$(RHIDE_TYPED_LIBS_SUFFIXES),$(RHIDE_TYPED_LIBS$(suff)))
RHIDE_TYPED_LIBS.C=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.F=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.adb=gnat
RHIDE_TYPED_LIBS.cc=$(RHIDE_TYPED_LIBS_$(RHIDE_OS).cc)
RHIDE_TYPED_LIBS.cpp=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.cxx=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.f=g2c m
RHIDE_TYPED_LIBS.for=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.fpp=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.ii=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.l=fl
RHIDE_TYPED_LIBS.m=objc
RHIDE_TYPED_LIBS.p=$(RHIDE_TYPED_LIBS_$(PASCAL_TYPE))
RHIDE_TYPED_LIBS.pas=$(RHIDE_TYPED_LIBS.p)
RHIDE_TYPED_LIBS.pp=$(RHIDE_TYPED_LIBS_FPC)
RHIDE_TYPED_LIBS_$(RHIDE_OS).cc=stdc++ m
RHIDE_TYPED_LIBS_DJGPP.cc=stdcxx m
RHIDE_TYPED_LIBS_FPC=fpc
RHIDE_TYPED_LIBS_GPC=gpc m
RHIDE_TYPED_LIBS_Linux.cc=stdc++ m
RHIDE_TYPED_LIBS_SUFFIXES=$(sort $(foreach item,$(PROJECT_ITEMS),$(suffix\
	$(item))))
_RHIDE_COMPILE_LINK_ADA=$(RHIDE_COMPILE_LINK_ADA_BIND);\
	$(RHIDE_COMPILE_LINK_ADA_LINK);   $(RHIDE_RM)\
	$(RHIDE_ADA_BIND_FILE)
%.o: %.c
	$(RHIDE_COMPILE.c.o)
%.o: %.i
	$(RHIDE_COMPILE_C)
%.o: %.cc
	$(RHIDE_COMPILE.cc.o)
%.o: %.cpp
	$(RHIDE_COMPILE.cpp.o)
%.o: %.cxx
	$(RHIDE_COMPILE.cxx.o)
%.o: %.C
	$(RHIDE_COMPILE.C.o)
%.o: %.ii
	$(RHIDE_COMPILE_CC)
%.o: %.s
	$(RHIDE_COMPILE.s.o)
%.o: %.S
	$(RHIDE_COMPILE_ASM)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.s: %.i
	$(RHIDE_COMPILE.i.s)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
%.o: %.pas
	$(RHIDE_COMPILE.pas.o)
%.o: %.p
	$(RHIDE_COMPILE.p.o)
%.o: %.pp
	$(RHIDE_COMPILE.pp.o)
%.s: %.pas
	$(RHIDE_COMPILE.pas.s)
%.o: %.m
	$(RHIDE_COMPILE_OBJC)
%.o: %.f
	$(RHIDE_COMPILE.f.o)
%.o: %.for
	$(RHIDE_COMPILE.for.o)
%.o: %.F
	$(RHIDE_COMPILE.F.o)
%.o: %.fpp
	$(RHIDE_COMPILE.fpp.o)
%.o: %.asm
	$(RHIDE_COMPILE.asm.o)
%.o: %.nsm
	$(RHIDE_COMPILE.nsm.o)
%.o: %.adb
	$(RHIDE_COMPILE.adb.o)
%.i: %.c
	$(RHIDE_COMPILE.c.i)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.ii: %.cc
	$(RHIDE_COMPILE.cc.ii)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.ii: %.cpp
	$(RHIDE_COMPILE.cpp.ii)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.ii: %.cxx
	$(RHIDE_COMPILE.cxx.ii)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.ii: %.C
	$(RHIDE_COMPILE.C.ii)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
include rhide.env
all::
clean::
	rm -f $(CLEAN_FILES)
DEPS_0= obj/lablchek.o obj/lablradi.o obj/snostate.o obj/tcheck2.o\
	obj/tmiclust.o obj/tsbutton.o obj/tschkarr.o obj/tschkbox.o\
	obj/tshscrol.o obj/tshzgrp.o obj/tsinplin.o obj/tsinplpi.o\
	obj/tslabel.o obj/tslider.o obj/tslistbo.o obj/tsradbot.o\
	obj/tssortlb.o obj/tssosslb.o obj/tstatext.o obj/tstextsc.o\
	obj/tstsorlb.o obj/tsvegrp.o obj/tsview.o obj/tsviewco.o\
	obj/ttextscr.o 
NO_LINK=
LINK_FILES=$(filter-out $(NO_LINK),$(DEPS_0))
libeasyd.a:: $(DEPS_0)
	$(RHIDE_COMPILE_ARCHIVE)
DEPS_1=lablchek.cc compatlayer.h easydia1.h easydiag.h tschkbox.h tslabel.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/checkbox.h tv/cluster.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/label.h tv/no_mss.h\
	tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/sitem.h tv/stddlg.h tv/streambl.h\
	tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h
obj/lablchek.o:: $(DEPS_1)
	$(RHIDE_COMPILE.cc.o)
DEPS_2=lablradi.cc compatlayer.h easydia1.h easydiag.h tslabel.h tsradbot.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/cluster.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/label.h tv/no_mss.h tv/nscoll.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/radiobtn.h tv/rect.h tv/sitem.h tv/stddlg.h tv/streambl.h\
	tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h
obj/lablradi.o:: $(DEPS_2)
	$(RHIDE_COMPILE.cc.o)
DEPS_3=snostate.cc compatlayer.h easydia1.h easydiag.h nostatex.h\
	settvuti.h snostate.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/rect.h tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/snostate.o:: $(DEPS_3)
	$(RHIDE_COMPILE.cc.o)
DEPS_4=tcheck2.cc compatlayer.h easydia1.h easydiag.h tcheck2.h tmiclust.h\
	tv.h tv/configtv.h tv/drawbuf.h tv/intl.h tv/ipstream.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/stddlg.h\
	tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h
obj/tcheck2.o:: $(DEPS_4)
	$(RHIDE_COMPILE.cc.o)
DEPS_5=tmiclust.cc compatlayer.h easydia1.h easydiag.h tmiclust.h tv.h\
	tv/collectn.h tv/configtv.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/palette.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/sitem.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h\
	tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h
obj/tmiclust.o:: $(DEPS_5)
	$(RHIDE_COMPILE.cc.o)
DEPS_6=tsbutton.cc compatlayer.h easydia1.h easydiag.h tsbutton.h tshzgrp.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/button.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h
obj/tsbutton.o:: $(DEPS_6)
	$(RHIDE_COMPILE.cc.o)
DEPS_7=tschkarr.cc compatlayer.h easydia1.h easydiag.h tcheck2.h tmiclust.h\
	tschkarr.h tsview.h tv.h tv/configtv.h tv/dialog.h tv/dialogs.h\
	tv/drawbuf.h tv/group.h tv/intl.h tv/ipstream.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h
obj/tschkarr.o:: $(DEPS_7)
	$(RHIDE_COMPILE.cc.o)
DEPS_8=tschkbox.cc compatlayer.h easydia1.h easydiag.h tschkbox.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/checkbox.h tv/cluster.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/sitem.h tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
obj/tschkbox.o:: $(DEPS_8)
	$(RHIDE_COMPILE.cc.o)
DEPS_9=tshscrol.cc compatlayer.h easydia1.h easydiag.h tshscrol.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/group.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/scrlbar.h tv/stddlg.h\
	tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h
obj/tshscrol.o:: $(DEPS_9)
	$(RHIDE_COMPILE.cc.o)
DEPS_10=tshzgrp.cc compatlayer.h easydia1.h easydiag.h tshzgrp.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/group.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/stddlg.h tv/streambl.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/tshzgrp.o:: $(DEPS_10)
	$(RHIDE_COMPILE.cc.o)
DEPS_11=tsinplin.cc compatlayer.h easydia1.h easydiag.h tsinplin.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/group.h tv/history.h tv/inputln.h\
	tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h
obj/tsinplin.o:: $(DEPS_11)
	$(RHIDE_COMPILE.cc.o)
DEPS_12=tsinplpi.cc compatlayer.h easydia1.h easydiag.h settvuti.h\
	tinppipe.h tsinplpi.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/group.h tv/history.h tv/inputln.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/stddlg.h tv/streambl.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/tsinplpi.o:: $(DEPS_12)
	$(RHIDE_COMPILE.cc.o)
DEPS_13=tslabel.cc compatlayer.h easydia1.h easydiag.h tslabel.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/group.h tv/intl.h tv/ipstream.h\
	tv/label.h tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/pstream.h tv/rect.h tv/stddlg.h\
	tv/streambl.h tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h
obj/tslabel.o:: $(DEPS_13)
	$(RHIDE_COMPILE.cc.o)
DEPS_14=tslider.cc compatlayer.h easydia1.h easydiag.h tslider.h tsview.h\
	tv.h tv/configtv.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/scrlbar.h tv/stddlg.h\
	tv/streambl.h tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h
obj/tslider.o:: $(DEPS_14)
	$(RHIDE_COMPILE.cc.o)
DEPS_15=tslistbo.cc compatlayer.h easydia1.h easydiag.h tslistbo.h\
	tssortva.h tsview.h tsviewco.h tv.h tv/app.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/no_mss.h\
	tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/scrlbar.h tv/stddlg.h tv/streambl.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/tslistbo.o:: $(DEPS_15)
	$(RHIDE_COMPILE.cc.o)
DEPS_16=tsradbot.cc compatlayer.h easydia1.h easydiag.h tsradbot.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/cluster.h tv/configtv.h tv/desktop.h\
	tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/pstream.h tv/radiobtn.h tv/rect.h\
	tv/sitem.h tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
obj/tsradbot.o:: $(DEPS_16)
	$(RHIDE_COMPILE.cc.o)
DEPS_17=tssortlb.cc compatlayer.h easydia1.h easydiag.h tslistbo.h\
	tssortlb.h tssortva.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/listbox.h tv/lstviewr.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/scrlbar.h tv/sortlibo.h\
	tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h
obj/tssortlb.o:: $(DEPS_17)
	$(RHIDE_COMPILE.cc.o)
DEPS_18=tssosslb.cc compatlayer.h easydia1.h easydiag.h setstack.h\
	settvuti.h tnocastc.h tslistbo.h tssortva.h tssosslb.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/group.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/scrlbar.h tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/tssosslb.o:: $(DEPS_18)
	$(RHIDE_COMPILE.cc.o)
DEPS_19=tstatext.cc compatlayer.h easydia1.h easydiag.h tstatext.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/group.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/stddlg.h tv/streambl.h\
	tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h
obj/tstatext.o:: $(DEPS_19)
	$(RHIDE_COMPILE.cc.o)
DEPS_20=tstextsc.cc compatlayer.h easydia1.h easydiag.h tstextsc.h tsview.h\
	tsviewco.h ttextscr.h tv.h tv/app.h tv/configtv.h tv/desktop.h\
	tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/object.h\
	tv/objects.h tv/opstream.h tv/palette.h tv/point.h tv/pstream.h\
	tv/rect.h tv/scrlbar.h tv/scroller.h tv/stddlg.h tv/streambl.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/tstextsc.o:: $(DEPS_20)
	$(RHIDE_COMPILE.cc.o)
DEPS_21=tstsorlb.cc compatlayer.h easydia1.h easydiag.h settvuti.h\
	tslistbo.h tssortva.h tstringa.h tstrlbox.h tstsorlb.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/group.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/scrlbar.h tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
obj/tstsorlb.o:: $(DEPS_21)
	$(RHIDE_COMPILE.cc.o)
DEPS_22=tsvegrp.cc compatlayer.h easydia1.h easydiag.h tsvegrp.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/group.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/stddlg.h tv/streambl.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/tsvegrp.o:: $(DEPS_22)
	$(RHIDE_COMPILE.cc.o)
DEPS_23=tsview.cc compatlayer.h easydia1.h easydiag.h tsview.h tv.h\
	tv/configtv.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/stddlg.h tv/streambl.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h
obj/tsview.o:: $(DEPS_23)
	$(RHIDE_COMPILE.cc.o)
DEPS_24=tsviewco.cc compatlayer.h easydia1.h easydiag.h tsview.h tsviewco.h\
	tv.h tv/app.h tv/applictn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h
obj/tsviewco.o:: $(DEPS_24)
	$(RHIDE_COMPILE.cc.o)
DEPS_25=ttextscr.cc compatlayer.h easydia1.h easydiag.h ttextscr.h tv.h\
	tv/configtv.h tv/drawbuf.h tv/event.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/palette.h tv/point.h tv/pstream.h tv/scrlbar.h tv/scroller.h\
	tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/yes_mss.h
obj/ttextscr.o:: $(DEPS_25)
	$(RHIDE_COMPILE.cc.o)
all:: libeasyd.a
