# This file is automatically generated by RHIDE 1.5
# created with the command:
# gpr2mak editor.gpr
vpath_src=../mainsrc ../names ../streams ../setedit ../setedit/names ../setedit/streams ../infview ../sdg ../settvuti ../extra ../mp3 ../include ../infview/include ../calcu e:/dj/contrib/tvision/classes /usr/src/tvision /usr/src/tvision/classes
vpath %.c $(vpath_src)
vpath %.cc $(vpath_src)
vpath %.cpp $(vpath_src)
vpath %.C $(vpath_src)
vpath %.cxx $(vpath_src)
vpath %.s $(vpath_src)
vpath %.S $(vpath_src)
vpath %.p $(vpath_src)
vpath %.pas $(vpath_src)
vpath %.f $(vpath_src)
vpath %.for $(vpath_src)
vpath %.F $(vpath_src)
vpath %.fpp $(vpath_src)
vpath %.i $(vpath_src)
vpath %.ii $(vpath_src)
vpath %.m $(vpath_src)
vpath %.asm $(vpath_src)
vpath %.nsm $(vpath_src)
vpath_header=../include ../setedit/include ../settvuti/include\
	../sdg/include ../infview/include $(TVISION_INC) ../extra\
	../easydiag ../librhuti $(SUPPORT_INC) ../mp3 ../calcu ../holidays
vpath %.h $(vpath_header)
vpath %.hpp $(vpath_header)
vpath %.ha $(vpath_header)
vpath %.hd $(vpath_header)
vpath_obj=obj
vpath %.o $(vpath_obj)
FLAGS_FOR_SUBPROJECTS=RHIDE_OS_="$(RHIDE_OS_)" CFLAGS="$(CFLAGS)"\
	CXXFLAGS="$(CXXFLAGS)" LDFLAGS="$(LDFLAGS)" CPPFLAGS="$(CPPFLAGS)"
RHIDE_OS=$(RHIDE_OS_)
ifeq ($(strip $(RHIDE_OS)),)
ifneq ($(strip $(DJDIR)),)
RHIDE_OS_:=DJGPP
else
RHIDE_OS_:=$(patsubst CYGWIN%,CYGWIN,$(shell uname))
endif
endif

INCLUDE_DIRS=../include ../setedit/include ../settvuti/include\
	../sdg/include ../infview/include $(TVISION_INC) ../extra\
	../easydiag ../librhuti $(SUPPORT_INC) ../mp3 ../calcu ../holidays
LIB_DIRS=$(RHIDE_OS_LIBS_PATH) -L.
C_DEBUG_FLAGS=
C_OPT_FLAGS=
C_WARN_FLAGS=
C_C_LANG_FLAGS=
C_CXX_LANG_FLAGS=
C_P_LANG_FLAGS=
C_FPC_LANG_FLAGS=
C_F_LANG_FLAGS=
C_ADA_LANG_FLAGS=
LIBS=
LD_EXTRA_FLAGS=
C_EXTRA_FLAGS=
LOCAL_OPT=$(subst ___~~~___, ,$(subst $(notdir $<)___,,$(filter $(notdir\
	$<)___%,$(LOCAL_OPTIONS))))

OBJFILES=obj/accehtml.o obj/advice.o obj/ampdiag.o obj/intermp3.o\
	obj/mp3list.o obj/mp3play.o obj/ascii.o obj/boardmix.o obj/bufun.o\
	obj/calcu.o obj/calendar.o obj/ceditor.o obj/codepage.o\
	obj/completi.o obj/debug.o obj/deedidia.o obj/doedidia.o\
	obj/dskascii.o obj/dskcalen.o obj/dskclip.o obj/dskclose.o\
	obj/dskedito.o obj/dskhelp.o obj/dskman.o obj/dskmessa.o\
	obj/dskmp3.o obj/dskwin.o obj/dstfile.o obj/dumpfile.o\
	obj/edcolor.o obj/edconst.o obj/edfonts.o obj/editdiag.o\
	obj/editmain.o obj/editmenu.o obj/editorfo.o obj/editpale.o\
	obj/editwind.o obj/edkeys.o obj/edmsg.o obj/edprefs.o obj/edprint.o\
	obj/edprj.o obj/edspecs.o obj/djmdr.o obj/dyncat.o obj/memmove.o\
	obj/mixer.o obj/mixersb.o obj/mixoss.o obj/stackdbg.o\
	obj/strncpyz.o obj/strndup.o obj/fstrcmp.o obj/getctxhl.o\
	obj/gzfiles.o obj/holidays.o obj/inf.o obj/infbase.o obj/manview.o\
	obj/nhiscoll.o obj/ninfview.o obj/ninfwind.o obj/nmanwind.o\
	obj/sinf.o obj/sman.o obj/intgrep.o obj/keytrans.o obj/linelen.o\
	obj/loadcle.o obj/loaddefl.o obj/loadfunc.o obj/loadnobkp.o\
	obj/loadshl.o obj/loadusew.o obj/macrocom.o obj/menuload.o\
	obj/mli.o obj/mliasimp.o obj/mlicsdg.o obj/mliediti.o\
	obj/mliedito.o obj/mlisdg.o obj/msignal.o obj/nceditor.o\
	obj/ndskwasc.o obj/ndskwcal.o obj/ndskwcli.o obj/ndskwclo.o\
	obj/ndskwedi.o obj/ndskwhel.o obj/ndskwman.o obj/ndskwmes.o\
	obj/ndskwmp3.o obj/ndskwprj.o obj/neditwin.o obj/nfileedi.o\
	obj/nsindica.o obj/ntedcol.o obj/parser.o obj/pathlist.o\
	obj/pathtool.o obj/pclipper.o obj/pmacros.o obj/pperl.o obj/pphp.o\
	obj/ppython.o obj/pvarious.o obj/pvhdl.o obj/runprog.o\
	obj/sceditor.o obj/scresave.o obj/sdginter.o obj/sdskasci.o\
	obj/sdskcale.o obj/sdskclip.o obj/sdskclos.o obj/sdskedit.o\
	obj/sdskhelp.o obj/sdskman.o obj/sdskmess.o obj/sdskmp3.o\
	obj/sdskprj.o obj/search.o obj/sedcolle.o obj/slpinter.o\
	obj/splinman.o obj/ssindica.o obj/ssyntax.o obj/tags.o\
	obj/tedcolle.o obj/tips.o obj/tpaltext.o obj/tsindica.o\
	obj/txhgen.o obj/winlistd.o
ALL_OBJFILES=obj/accehtml.o obj/advice.o obj/ampdiag.o obj/intermp3.o\
	obj/mp3list.o obj/mp3play.o obj/ascii.o obj/boardmix.o obj/bufun.o\
	obj/calcu.o obj/calendar.o obj/ceditor.o obj/codepage.o\
	obj/completi.o obj/debug.o obj/deedidia.o obj/doedidia.o\
	obj/dskascii.o obj/dskcalen.o obj/dskclip.o obj/dskclose.o\
	obj/dskedito.o obj/dskhelp.o obj/dskman.o obj/dskmessa.o\
	obj/dskmp3.o obj/dskwin.o obj/dstfile.o obj/dumpfile.o\
	obj/lablchek.o obj/lablradi.o obj/snostate.o obj/tcheck2.o\
	obj/tmiclust.o obj/tsbutton.o obj/tschkarr.o obj/tschkbox.o\
	obj/tshscrol.o obj/tshzgrp.o obj/tsinplin.o obj/tsinplpi.o\
	obj/tslabel.o obj/tslider.o obj/tslistbo.o obj/tsradbot.o\
	obj/tssortlb.o obj/tssosslb.o obj/tstatext.o obj/tstextsc.o\
	obj/tstsorlb.o obj/tsvegrp.o obj/tsview.o obj/tsviewco.o\
	obj/ttextscr.o obj/edcolor.o obj/edconst.o obj/edfonts.o\
	obj/editdiag.o obj/editmain.o obj/editmenu.o obj/editorfo.o\
	obj/editpale.o obj/editwind.o obj/edkeys.o obj/edmsg.o\
	obj/edprefs.o obj/edprint.o obj/edprj.o obj/edspecs.o obj/djmdr.o\
	obj/dyncat.o obj/memmove.o obj/mixer.o obj/mixersb.o obj/mixoss.o\
	obj/stackdbg.o obj/strncpyz.o obj/strndup.o obj/fstrcmp.o\
	obj/getctxhl.o obj/gzfiles.o obj/holidays.o obj/inf.o obj/infbase.o\
	obj/manview.o obj/nhiscoll.o obj/ninfview.o obj/ninfwind.o\
	obj/nmanwind.o obj/sinf.o obj/sman.o obj/intgrep.o obj/keytrans.o\
	obj/abstorel.o obj/back2sl.o obj/basename.o obj/fexpand.o obj/io.o\
	obj/specs.o obj/splitfn.o obj/stricat.o obj/stridown.o\
	obj/stridup.o obj/strifree.o obj/linelen.o obj/loadcle.o\
	obj/loaddefl.o obj/loadfunc.o obj/loadnobkp.o obj/loadshl.o\
	obj/loadusew.o obj/macrocom.o obj/menuload.o obj/mli.o\
	obj/mliasimp.o obj/mlicsdg.o obj/mliediti.o obj/mliedito.o\
	obj/mlisdg.o obj/msignal.o obj/nceditor.o obj/ndskwasc.o\
	obj/ndskwcal.o obj/ndskwcli.o obj/ndskwclo.o obj/ndskwedi.o\
	obj/ndskwhel.o obj/ndskwman.o obj/ndskwmes.o obj/ndskwmp3.o\
	obj/ndskwprj.o obj/neditwin.o obj/nfileedi.o obj/nsindica.o\
	obj/ntedcol.o obj/parser.o obj/pathlist.o obj/pathtool.o\
	obj/pclipper.o obj/pmacros.o obj/pperl.o obj/pphp.o obj/ppython.o\
	obj/pvarious.o obj/pvhdl.o obj/runprog.o obj/sceditor.o\
	obj/scresave.o obj/sdginter.o obj/sdskasci.o obj/sdskcale.o\
	obj/sdskclip.o obj/sdskclos.o obj/sdskedit.o obj/sdskhelp.o\
	obj/sdskman.o obj/sdskmess.o obj/sdskmp3.o obj/sdskprj.o\
	obj/search.o obj/sedcolle.o obj/diaghelp.o obj/dktclock.o\
	obj/fileopen.o obj/fiopeaid.o obj/inputsca.o obj/ninputsc.o\
	obj/nostatex.o obj/nprogbar.o obj/nprogres.o obj/ntnocast.o\
	obj/ntnosost.o obj/setstack.o obj/sprogbar.o obj/sprogres.o\
	obj/stnocast.o obj/stnonost.o obj/tdiagaid.o obj/tdiagrow.o\
	obj/tinppipe.o obj/tnocastc.o obj/tnosostr.o obj/tprogbar.o\
	obj/tprogdia.o obj/tprogrdi.o obj/tprogres.o obj/tstrlbox.o\
	obj/uisarray.o obj/ussarray.o obj/viewplus.o obj/slpinter.o\
	obj/splinman.o obj/ssindica.o obj/ssyntax.o obj/tags.o\
	obj/tedcolle.o obj/tips.o obj/tpaltext.o obj/tsindica.o\
	obj/txhgen.o obj/winlistd.o
LIBRARIES=libeasyd.a librhuti.a libsettv.a
SOURCE_NAME=$<
OUTFILE=$@
SPECIAL_CFLAGS=
SPECIAL_LDFLAGS=
PROG_ARGS=--no-redirect --no-mouse-hook -S --stack-dbg=0
SRC_DIRS=../mainsrc ../names ../streams ../setedit ../setedit/names\
	../setedit/streams ../infview ../sdg ../settvuti ../extra ../mp3\
	../include ../infview/include ../calcu\
	e:/dj/contrib/tvision/classes /usr/src/tvision\
	/usr/src/tvision/classes
WUC=
EDITORS=
MAIN_TARGET=editor.exe
PROJECT_ITEMS=accehtml.cc advice.cc amp3.gpr ascii.cc boardmix.cc bufun.cc\
	calcu.cc calendar.cc ceditor.cc codepage.cc completi.cc debug.cc\
	deedidia.cc doedidia.cc dskascii.cc dskcalen.cc dskclip.cc\
	dskclose.cc dskedito.cc dskhelp.cc dskman.cc dskmessa.cc dskmp3.cc\
	dskwin.cc dstfile.cc dumpfile.cc easydiag.gpr edcolor.cc edconst.cc\
	edfonts.cc editdiag.cc editmain.cc editmenu.cc editorfo.cc\
	editpale.cc editwind.cc edkeys.cc edmsg.cc edprefs.cc edprint.cc\
	edprj.cc edspecs.cc extra.gpr fstrcmp.c getctxhl.cc gzfiles.cc\
	holidays.cc inffd.gpr intgrep.cc keytrans.cc librhuti.gpr\
	linelen.cc loadcle.cc loaddefl.cc loadfunc.cc loadnobkp.cc\
	loadshl.cc loadusew.cc macrocom.cc menuload.cc mli.cc mliasimp.cc\
	mlicsdg.cc mliediti.cc mliedito.cc mlisdg.cc msignal.cc nceditor.cc\
	ndskwasc.cc ndskwcal.cc ndskwcli.cc ndskwclo.cc ndskwedi.cc\
	ndskwhel.cc ndskwman.cc ndskwmes.cc ndskwmp3.cc ndskwprj.cc\
	neditwin.cc nfileedi.cc nsindica.cc ntedcol.cc parser.c pathlist.cc\
	pathtool.cc pclipper.cc pmacros.cc pperl.cc pphp.cc ppython.cc\
	pvarious.cc pvhdl.cc runprog.cc sceditor.cc scresave.cc sdginter.cc\
	sdskasci.cc sdskcale.cc sdskclip.cc sdskclos.cc sdskedit.cc\
	sdskhelp.cc sdskman.cc sdskmess.cc sdskmp3.cc sdskprj.cc search.cc\
	sedcolle.cc settv.gpr slpinter.cc splinman.cc ssindica.cc\
	ssyntax.cc tags.cc tedcolle.cc tips.cc tpaltext.cc tsindica.cc\
	txhgen.cc winlistd.cc
DEFAULT_MASK=*
RHIDE_BIN_DIR=/usr/bin
PASCAL_TYPE=GPC
GET_HOME=$(HOME)
CLEAN_FILES=$(MAIN_TARGET) $(OBJFILES)
DEFAULT_GREP_MASK=*.[cfhmnps]*
RHIDE_ADA_BIND_FILE=$(addprefix _,$(setsuffix .c,$(OUTFILE)))
RHIDE_AR=ar
RHIDE_ARFLAGS=rcs
RHIDE_AS=$(RHIDE_GCC)
RHIDE_CO=$(shell co -q $(co_arg))
RHIDE_COMPILE.C.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.C.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.C.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.F.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.adb.o=$(RHIDE_COMPILE_ADA)
RHIDE_COMPILE.asm.o=$(RHIDE_COMPILE.nsm.o)
RHIDE_COMPILE.c.i=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.c.o=$(RHIDE_COMPILE_C)
RHIDE_COMPILE.c.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.cc.ii=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cc.o=$(RHIDE_COMPILE_CC)
RHIDE_COMPILE.cc.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cpp.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cpp.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cpp.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.cxx.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cxx.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cxx.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.f.o=$(RHIDE_COMPILE_FORTRAN)
RHIDE_COMPILE.for.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.fpp.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.i.s=$(RHIDE_COMPILE.c.s)
RHIDE_COMPILE.ii.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.nsm.o=$(RHIDE_COMPILE_NASM)
RHIDE_COMPILE.p.o=$(RHIDE_COMPILE_PASCAL)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pas.s=$(RHIDE_COMPILE.pas.s.$(PASCAL_TYPE))
RHIDE_COMPILE.pas.s.FPC=$(RHIDE_COMPILE_FPC) -a -s
RHIDE_COMPILE.pas.s.GPC=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_GPC))
RHIDE_COMPILE.pp.o=$(RHIDE_COMPILE_FPC)
RHIDE_COMPILE.s.o=$(RHIDE_COMPILE_ASM)
RHIDE_COMPILE_ADA=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  $(C_ADA_LANG_FLAGS)  $(RHIDE_OS_CFLAGS) $(CPPFLAGS)\
	$(CFLAGS) -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ARCHIVE=$(RHIDE_AR) $(RHIDE_ARFLAGS) $(OUTFILE)\
	$(ALL_OBJFILES)
RHIDE_COMPILE_ASM=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ASM_FORCE=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) -x assembler\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_C=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(RHIDE_OS_CFLAGS)  $(CPPFLAGS) $(CFLAGS) $(LOCAL_OPT) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_CC=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(RHIDE_OS_CXXFLAGS)\
	$(CPPFLAGS) $(CXXFLAGS) $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_CC_FORCE=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(RHIDE_OS_CXXFLAGS)\
	$(CPPFLAGS) $(CXXFLAGS) -x c++ $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_C_FORCE=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x c $(RHIDE_OS_CFLAGS)  $(CPPFLAGS) $(CFLAGS) $(LOCAL_OPT) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN_FORCE=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x f77 $(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FPC=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -E- $(SOURCE_NAME)
RHIDE_COMPILE_FPC_FORCE=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -B -E-\
	$(SOURCE_NAME)
RHIDE_COMPILE_GPC=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_GPC_FORCE=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) -x pascal\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_ADA=gnatbl $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(setsuffix .ali,$(OUTFILE)) $(LIBRARIES) $(LDFLAGS) \
	$(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_ADA_BIND=$(RHIDE_GNATBIND) -o $(RHIDE_ADA_BIND_FILE)\
	$(setsuffix .ali,$(OUTFILE))
RHIDE_COMPILE_LINK_ADA_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(RHIDE_ADA_BIND_FILE) $(OBJFILES) $(LIBRARIES)\
	$(LDFLAGS)  $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_DLL=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)  \
	$(RHIDE_SHARED_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_FPC=echo 'separate linking for FPK is not supported.\
	Please define a main source file in Project/Primary file.' 1>&2
RHIDE_COMPILE_LINK_FPC_AUTOMAKE=$(RHIDE_FPC) -o$(OUTFILE) $(SOURCE_NAME)\
	$(RHIDE_FPC_FLAGS) -E+
RHIDE_COMPILE_LINK_GPC=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS)\
	-o $(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(RHIDE_LDFLAGS) $(LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_GPC_AUTOMAKE=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS)  -o\
	$(OUTFILE) --automake $(RHIDE_GPC_FLAGS)  $(SOURCE_NAME)\
	$(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_PASCAL=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE))
RHIDE_COMPILE_LINK_PASCAL_AUTOMAKE=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE)_AUTOMAKE)
RHIDE_COMPILE_NASM=$(RHIDE_NASM) -f $(RHIDE_NASM_TARGET) $(LOCAL_OPT) -o\
	$(OUTFILE)  $(SOURCE_NAME)
RHIDE_COMPILE_PASCAL=$(RHIDE_COMPILE_$(PASCAL_TYPE))
RHIDE_COMPILE_PASCAL_FORCE=$(RHIDE_COMPILE_$(PASCAL_TYPE)_FORCE)
RHIDE_CONFIG_DIRS=. $(RHIDE_SHARE) $(GET_HOME)   $(RHIDE_CONFIG_DIRS_COMMON)\
	 $(addsuffix /SET,$(RHIDE_CONFIG_DIRS_COMMON))  $(SET_FILES)
RHIDE_CONFIG_DIRS_$(RHIDE_OS)=/usr/local/share/rhide /usr/share/rhide \
	/local/share/rhide /share/rhide
RHIDE_CONFIG_DIRS_COMMON=$(RHIDE_CONFIG_DIRS_$(RHIDE_OS))\
	$(RHIDE_BIN_DIR)/../share/rhide
RHIDE_CONFIG_DIRS_DJGPP=$(DJDIR)/share/rhide
RHIDE_CONFIG_DIRS_Linux=/usr/local/share/rhide /usr/share/rhide \
	/local/share/rhide /share/rhide
RHIDE_EMPTY=
RHIDE_FPC=ppc386
RHIDE_FPC_FLAGS=$(C_FPC_LANG_FLAGS) $(LOCAL_OPT) $(addprefix\
	-Up,$(INCLUDE_DIRS))  $(C_EXTRA_FLAGS)
RHIDE_FPC_LIBDIRS=$(RHIDE_FPC_LIBDIRS_$(RHIDE_OS))
RHIDE_FPC_LIBDIRS_$(RHIDE_OS)=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LIBDIRS_DJGPP=$(DJDIR)/lib
RHIDE_FPC_LIBDIRS_Linux=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LINK_FLAGS=$(RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS))
RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS)=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_DJGPP=-O coff-go32-exe $(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_Linux=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FSDB=fsdb $(OUTFILE) $(addprefix -p ,$(SRC_DIRS)) $(PROG_ARGS)
RHIDE_G77=g77
RHIDE_GCC=gcc
RHIDE_GDB=gdb $(OUTFILE) $(addprefix -d ,$(SRC_DIRS))
RHIDE_GNATBIND=gnatbind
RHIDE_GPC=gpc
RHIDE_GPC_FLAGS=$(RHIDE_INCLUDES) $(C_DEBUG_FLAGS) $(C_OPT_FLAGS)\
	$(C_WARN_FLAGS)  $(C_P_LANG_FLAGS) $(C_EXTRA_FLAGS)
RHIDE_GPROF=gprof $(OUTFILE)
RHIDE_GREP=grep -n $(prompt arguments for GREP,$(WUC) $(DEFAULT_GREP_MASK))
RHIDE_GXX=$(RHIDE_GCC)
RHIDE_INCLUDES=$(SPECIAL_CFLAGS) $(addprefix -I,$(INCLUDE_DIRS))
RHIDE_LD=$(RHIDE_GCC)
RHIDE_LDFLAGS=$(SPECIAL_LDFLAGS) $(addprefix -Xlinker ,$(LD_EXTRA_FLAGS))
RHIDE_LD_FPC=$(RHIDE_FPC) -E+
RHIDE_LD_PASCAL=gpc
RHIDE_LIBDIRS=$(addprefix -L,$(LIB_DIRS))
RHIDE_LIBS=$(addprefix -l,$(LIBS) $(RHIDE_TYPED_LIBS) $(RHIDE_OS_LIBS))
RHIDE_NASM=nasm
RHIDE_NASM_TARGET=$(RHIDE_NASM_TARGET_$(RHIDE_OS))
RHIDE_NASM_TARGET_DJGPP=coff
RHIDE_NASM_TARGET_Linux=elf
RHIDE_PATH_SEPARATOR=$(RHIDE_PATH_SEPARATOR_$(RHIDE_OS))
RHIDE_PATH_SEPARATOR_$(RHIDE_OS)=:
RHIDE_PATH_SEPARATOR_DJGPP=;
RHIDE_PATH_SEPARATOR_Linux=:
RHIDE_RLOG=$(shell rlog -R $(rlog_arg))
RHIDE_RM=rm
RHIDE_SHARED_LDFLAGS=$(RHIDE_SHARED_LDFLAGS_$(RHIDE_OS))
RHIDE_SHARED_LDFLAGS_$(RHIDE_OS)=
RHIDE_SHARED_LDFLAGS_Linux=-shared
RHIDE_SHARED_LDFLAGS_Linux=
RHIDE_SPACE=$(RHIDE_EMPTY) $(RHIDE_EMPTY)
RHIDE_STANDARD_INCLUDES=$(RHIDE_STANDARD_INCLUDES_$(RHIDE_OS))
RHIDE_STANDARD_INCLUDES_$(RHIDE_OS)=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_STANDARD_INCLUDES_DJGPP=$(addprefix $(DJDIR)/,include include/sys\
	lang/cxx lang/cxx/std)
RHIDE_STANDARD_INCLUDES_Linux=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_TYPED_LIBS=$(foreach\
	suff,$(RHIDE_TYPED_LIBS_SUFFIXES),$(RHIDE_TYPED_LIBS$(suff)))
RHIDE_TYPED_LIBS.C=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.F=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.adb=gnat
RHIDE_TYPED_LIBS.cc=$(RHIDE_TYPED_LIBS_$(RHIDE_OS).cc)
RHIDE_TYPED_LIBS.cpp=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.cxx=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.f=g2c m
RHIDE_TYPED_LIBS.for=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.fpp=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.ii=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.l=fl
RHIDE_TYPED_LIBS.m=objc
RHIDE_TYPED_LIBS.p=$(RHIDE_TYPED_LIBS_$(PASCAL_TYPE))
RHIDE_TYPED_LIBS.pas=$(RHIDE_TYPED_LIBS.p)
RHIDE_TYPED_LIBS.pp=$(RHIDE_TYPED_LIBS_FPC)
RHIDE_TYPED_LIBS_$(RHIDE_OS).cc=stdc++ m
RHIDE_TYPED_LIBS_DJGPP.cc=stdcxx m
RHIDE_TYPED_LIBS_FPC=fpc
RHIDE_TYPED_LIBS_GPC=gpc m
RHIDE_TYPED_LIBS_Linux.cc=stdc++ m
RHIDE_TYPED_LIBS_SUFFIXES=$(sort $(foreach item,$(PROJECT_ITEMS),$(suffix\
	$(item))))
_RHIDE_COMPILE_LINK_ADA=$(RHIDE_COMPILE_LINK_ADA_BIND);\
	$(RHIDE_COMPILE_LINK_ADA_LINK);   $(RHIDE_RM)\
	$(RHIDE_ADA_BIND_FILE)
%.o: %.c
	$(RHIDE_COMPILE.c.o)
%.o: %.i
	$(RHIDE_COMPILE_C)
%.o: %.cc
	$(RHIDE_COMPILE.cc.o)
%.o: %.cpp
	$(RHIDE_COMPILE.cpp.o)
%.o: %.cxx
	$(RHIDE_COMPILE.cxx.o)
%.o: %.C
	$(RHIDE_COMPILE.C.o)
%.o: %.ii
	$(RHIDE_COMPILE_CC)
%.o: %.s
	$(RHIDE_COMPILE.s.o)
%.o: %.S
	$(RHIDE_COMPILE_ASM)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.s: %.i
	$(RHIDE_COMPILE.i.s)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
%.o: %.pas
	$(RHIDE_COMPILE.pas.o)
%.o: %.p
	$(RHIDE_COMPILE.p.o)
%.o: %.pp
	$(RHIDE_COMPILE.pp.o)
%.s: %.pas
	$(RHIDE_COMPILE.pas.s)
%.o: %.m
	$(RHIDE_COMPILE_OBJC)
%.o: %.f
	$(RHIDE_COMPILE.f.o)
%.o: %.for
	$(RHIDE_COMPILE.for.o)
%.o: %.F
	$(RHIDE_COMPILE.F.o)
%.o: %.fpp
	$(RHIDE_COMPILE.fpp.o)
%.o: %.asm
	$(RHIDE_COMPILE.asm.o)
%.o: %.nsm
	$(RHIDE_COMPILE.nsm.o)
%.o: %.adb
	$(RHIDE_COMPILE.adb.o)
%.i: %.c
	$(RHIDE_COMPILE.c.i)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.ii: %.cc
	$(RHIDE_COMPILE.cc.ii)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.ii: %.cpp
	$(RHIDE_COMPILE.cpp.ii)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.ii: %.cxx
	$(RHIDE_COMPILE.cxx.ii)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.ii: %.C
	$(RHIDE_COMPILE.C.ii)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
include rhide.env
all::
clean::
	rm -f $(CLEAN_FILES)
DEPS_0= obj/accehtml.o obj/advice.o obj/ampdiag.o obj/intermp3.o\
	obj/mp3list.o obj/mp3play.o obj/ascii.o obj/boardmix.o obj/bufun.o\
	obj/calcu.o obj/calendar.o obj/ceditor.o obj/codepage.o\
	obj/completi.o obj/debug.o obj/deedidia.o obj/doedidia.o\
	obj/dskascii.o obj/dskcalen.o obj/dskclip.o obj/dskclose.o\
	obj/dskedito.o obj/dskhelp.o obj/dskman.o obj/dskmessa.o\
	obj/dskmp3.o obj/dskwin.o obj/dstfile.o obj/dumpfile.o\
	obj/edcolor.o obj/edconst.o obj/edfonts.o obj/editdiag.o\
	obj/editmain.o obj/editmenu.o obj/editorfo.o obj/editpale.o\
	obj/editwind.o obj/edkeys.o obj/edmsg.o obj/edprefs.o obj/edprint.o\
	obj/edprj.o obj/edspecs.o obj/djmdr.o obj/dyncat.o obj/memmove.o\
	obj/mixer.o obj/mixersb.o obj/mixoss.o obj/stackdbg.o\
	obj/strncpyz.o obj/strndup.o obj/fstrcmp.o obj/getctxhl.o\
	obj/gzfiles.o obj/holidays.o obj/inf.o obj/infbase.o obj/manview.o\
	obj/nhiscoll.o obj/ninfview.o obj/ninfwind.o obj/nmanwind.o\
	obj/sinf.o obj/sman.o obj/intgrep.o obj/keytrans.o obj/linelen.o\
	obj/loadcle.o obj/loaddefl.o obj/loadfunc.o obj/loadnobkp.o\
	obj/loadshl.o obj/loadusew.o obj/macrocom.o obj/menuload.o\
	obj/mli.o obj/mliasimp.o obj/mlicsdg.o obj/mliediti.o\
	obj/mliedito.o obj/mlisdg.o obj/msignal.o obj/nceditor.o\
	obj/ndskwasc.o obj/ndskwcal.o obj/ndskwcli.o obj/ndskwclo.o\
	obj/ndskwedi.o obj/ndskwhel.o obj/ndskwman.o obj/ndskwmes.o\
	obj/ndskwmp3.o obj/ndskwprj.o obj/neditwin.o obj/nfileedi.o\
	obj/nsindica.o obj/ntedcol.o obj/parser.o obj/pathlist.o\
	obj/pathtool.o obj/pclipper.o obj/pmacros.o obj/pperl.o obj/pphp.o\
	obj/ppython.o obj/pvarious.o obj/pvhdl.o obj/runprog.o\
	obj/sceditor.o obj/scresave.o obj/sdginter.o obj/sdskasci.o\
	obj/sdskcale.o obj/sdskclip.o obj/sdskclos.o obj/sdskedit.o\
	obj/sdskhelp.o obj/sdskman.o obj/sdskmess.o obj/sdskmp3.o\
	obj/sdskprj.o obj/search.o obj/sedcolle.o obj/slpinter.o\
	obj/splinman.o obj/ssindica.o obj/ssyntax.o obj/tags.o\
	obj/tedcolle.o obj/tips.o obj/tpaltext.o obj/tsindica.o\
	obj/txhgen.o obj/winlistd.o libeasyd.a librhuti.a libsettv.a
NO_LINK=
LINK_FILES=$(filter-out $(NO_LINK),$(DEPS_0))
editor.exe:: $(DEPS_0)
	$(RHIDE_COMPILE_LINK)
DEPS_1=accehtml.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h compatlayer.h\
	pmcoll.h sarray.h setapp.h setstack.h settvuti.h sindicat.h\
	tnocastc.h tstringa.h tv.h tv/app.h tv/applictn.h tv/codepage.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/parttree.h tv/point.h tv/program.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/ssc_streams.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h ucdefs.h viewplus.h
obj/accehtml.o:: $(DEPS_1)
	$(RHIDE_COMPILE.cc.o)
DEPS_2=advice.cc advice.cc compatlayer.h easydia1.h easydiag.h edspecs.h\
	setapp.h settvuti.h tsbutton.h tschkbox.h tshzgrp.h tslabel.h\
	tslistbo.h tssortva.h tstatext.h tstringa.h tstrlbox.h tstsorlb.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/applictn.h tv/button.h\
	tv/checkbox.h tv/cluster.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h tv/no_mss.h\
	tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/scrlbar.h tv/sitem.h\
	tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
obj/advice.o:: $(DEPS_2)
	$(RHIDE_COMPILE.cc.o)
DEPS_3=
.PHONY: amp3.gpr.force
all:: amp3.gpr.force
amp3.gpr.force:
	$(MAKE) -f amp3.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_4=ascii.cc ascii.cc ascii.h compatlayer.h dskwin.h setapp.h tv.h\
	tv/app.h tv/configtv.h tv/drawbuf.h tv/event.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/stddlg.h tv/streambl.h\
	tv/strmblcl.h tv/system.h tv/tkeys.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h
obj/ascii.o:: $(DEPS_4)
	$(RHIDE_COMPILE.cc.o)
DEPS_5=boardmix.cc boardmix.cc compatlayer.h configed.h easydia1.h\
	easydiag.h mixer.h setapp.h tsbutton.h tschkbox.h tslider.h\
	tstatext.h tsview.h tsviewco.h tv.h tv/app.h tv/button.h\
	tv/checkbox.h tv/cluster.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/fpbase.h tv/fpstream.h\
	tv/group.h tv/intl.h tv/iopstrm.h tv/ipstream.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/scrlbar.h tv/sitem.h\
	tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
obj/boardmix.o:: $(DEPS_5)
	$(RHIDE_COMPILE.cc.o)
DEPS_6=bufun.cc bufun.cc bufun.h ced_coma.h ced_exte.h ced_pcre.h\
	ceditint.h ceditor.h compatlayer.h configed.h easydia1.h easydiag.h\
	edmsg.h setapp.h setstack.h settvuti.h splinman.h tdiagrow.h\
	tnocastc.h tsbutton.h tshzgrp.h tslabel.h tslistbo.h tssortva.h\
	tssosslb.h tstatext.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/applictn.h tv/button.h tv/codepage.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/label.h tv/listbox.h\
	tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/parttree.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h
obj/bufun.o:: $(DEPS_6)
	$(RHIDE_COMPILE.cc.o)
DEPS_7=calcu.cc calcu.cc calcu.h ced_clas.h ced_exte.h ced_pcre.h\
	ceditint.h ceditor.h compatlayer.h configed.h edhists.h editcoma.h\
	pmcoll.h sarray.h setapp.h setstack.h settvuti.h sindicat.h\
	tinppipe.h tnocastc.h tstringa.h tv.h tv/app.h tv/applictn.h\
	tv/button.h tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/history.h\
	tv/indicato.h tv/inputln.h tv/intl.h tv/ipstream.h tv/label.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/program.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/calcu.o:: $(DEPS_7)
	$(RHIDE_COMPILE.cc.o)
DEPS_8=calendar.cc calendar.cc calendar.h compatlayer.h datetools.h\
	editcoma.h tv.h tv/configtv.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/stddlg.h tv/streambl.h\
	tv/strmblcl.h tv/system.h tv/tkeyext.h tv/tkeys.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h
obj/calendar.o:: $(DEPS_8)
	$(RHIDE_COMPILE.cc.o)
DEPS_9=ceditor.cc advice.h bufun.h ced_clas.h ced_coma.h ced_exte.h\
	ced_inte.h ced_pcre.h ceditint.h ceditor.cc ceditor.h codepage.h\
	compatlayer.h configed.h dyncat.h edhists.h gzfiles.h keytrans.h\
	loadkbin.h loadshl.h pathtool.h pmcoll.h rhutils.h sarray.h\
	setconst.h setstack.h settvuti.h sindicat.h slpinter.h splinman.h\
	tnocastc.h tprogdia.h tstringa.h tstrlbox.h tv.h tv/app.h\
	tv/cmdset.h tv/codepage.h tv/collectn.h tv/colorsel.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/filedlg.h tv/findrepl.h tv/gkey.h tv/group.h tv/indicato.h\
	tv/intl.h tv/ipstream.h tv/lstviewr.h tv/menubox.h tv/menuitem.h\
	tv/menus.h tv/menuview.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/osclipboard.h tv/palette.h tv/parttree.h tv/point.h tv/program.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/screen.h tv/scrlbar.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h\
	tv/submenu.h tv/system.h tv/tkeys.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/ceditor.o:: $(DEPS_9)
	$(RHIDE_COMPILE.cc.o)
DEPS_10=codepage.cc calendar.h ced_clas.h ced_exte.h ced_inte.h ced_pcre.h\
	ceditint.h ceditor.h codepage.cc compatlayer.h configed.h mp3play.h\
	pmcoll.h sarray.h setapp.h setstack.h settvuti.h sindicat.h\
	tnocastc.h tprogdia.h tstringa.h tv.h tv/app.h tv/applictn.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/fontcoll.h tv/group.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/program.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/screen.h tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/codepage.o:: $(DEPS_10)
	$(RHIDE_COMPILE.cc.o)
DEPS_11=completi.cc ced_clas.h ced_exte.h ced_inte.h ced_pcre.h ceditor.h\
	compatlayer.h completi.cc completi.h pmcoll.h sarray.h setstack.h\
	settvuti.h sindicat.h tnocastc.h tstringa.h tv.h tv/app.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/palette.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
obj/completi.o:: $(DEPS_11)
	$(RHIDE_COMPILE.cc.o)
DEPS_12=debug.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h compatlayer.h\
	debug.cc debug.h dskwin.h dyncat.h easydia1.h easydiag.h edhists.h\
	editcoma.h edmsg.h nostatex.h pathlist.h pmcoll.h sarray.h setapp.h\
	setstack.h settvuti.h sindicat.h splinman.h tinppipe.h tnocastc.h\
	tsbutton.h tshzgrp.h tsinplin.h tsinplpi.h tslabel.h tstatext.h\
	tstringa.h tstrlbox.h tsvegrp.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/applictn.h tv/button.h tv/cmdset.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/history.h tv/indicato.h tv/inputln.h\
	tv/intl.h tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/parttree.h tv/point.h tv/program.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/screen.h tv/scrlbar.h\
	tv/scroller.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strmblcl.h\
	tv/strncoll.h tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/debug.o:: $(DEPS_12)
	$(RHIDE_COMPILE.cc.o)
DEPS_13=deedidia.cc ced_clas.h ced_coma.h ced_exte.h ced_inte.h ced_pcre.h\
	ceditint.h ceditor.h compatlayer.h configed.h deedidia.cc\
	diaghelp.h easydia1.h easydiag.h edhists.h editcoma.h pmcoll.h\
	sarray.h setapp.h setconst.h setstack.h settvuti.h sindicat.h\
	tinppipe.h tnocastc.h tsbutton.h tschkbox.h tshzgrp.h tsinplin.h\
	tsinplpi.h tslabel.h tslistbo.h tsradbot.h tssortlb.h tssortva.h\
	tstatext.h tstringa.h tstrlbox.h tstsorlb.h tsvegrp.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/applictn.h tv/button.h tv/checkbox.h\
	tv/cluster.h tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/fpbase.h tv/fpstream.h\
	tv/group.h tv/history.h tv/indicato.h tv/inputln.h tv/intl.h\
	tv/iopstrm.h tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/program.h tv/pstream.h\
	tv/radiobtn.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sitem.h\
	tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/sttctext.h tv/system.h tv/tkeys.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/deedidia.o:: $(DEPS_13)
	$(RHIDE_COMPILE.cc.o)
DEPS_14=doedidia.cc bufun.h ced_coma.h ced_exte.h ced_pcre.h ceditint.h\
	ceditor.h compatlayer.h configed.h doedidia.cc edhists.h fileopen.h\
	fiopeaid.h setconst.h setstack.h settvuti.h tnocastc.h tv.h\
	tv/app.h tv/collectn.h tv/configtv.h tv/desktop.h tv/drawbuf.h\
	tv/event.h tv/fpbase.h tv/fpstream.h tv/group.h tv/intl.h\
	tv/iopstrm.h tv/ipstream.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/yes_mss.h
obj/doedidia.o:: $(DEPS_14)
	$(RHIDE_COMPILE.cc.o)
DEPS_15=dskascii.cc ascii.h ceditint.h ceditor.h compatlayer.h configed.h\
	dskascii.cc dskascii.h dskwin.h setapp.h settvuti.h tv.h tv/app.h\
	tv/configtv.h tv/desktop.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/program.h tv/pstream.h tv/rect.h tv/stddlg.h\
	tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h
obj/dskascii.o:: $(DEPS_15)
	$(RHIDE_COMPILE.cc.o)
DEPS_16=dskcalen.cc calendar.h ceditint.h ceditor.h compatlayer.h\
	configed.h dskcalen.cc dskcalen.h dskwin.h setapp.h settvuti.h tv.h\
	tv/app.h tv/configtv.h tv/desktop.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h
obj/dskcalen.o:: $(DEPS_16)
	$(RHIDE_COMPILE.cc.o)
DEPS_17=dskclip.cc ced_clas.h ced_exte.h ced_pcre.h ceditint.h ceditor.h\
	compatlayer.h configed.h dskclip.cc dskclip.h dskwin.h pmcoll.h\
	sarray.h setapp.h setstack.h settvuti.h sindicat.h tnocastc.h\
	tstringa.h tv.h tv/app.h tv/applictn.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/program.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/screen.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
obj/dskclip.o:: $(DEPS_17)
	$(RHIDE_COMPILE.cc.o)
DEPS_18=dskclose.cc ced_clas.h ced_exte.h ced_pcre.h ceditint.h ceditor.h\
	compatlayer.h configed.h dskclose.cc dskclose.h dskwin.h edcollec.h\
	pmcoll.h sarray.h setapp.h setstack.h settvuti.h sindicat.h\
	tnocastc.h tstringa.h tv.h tv/app.h tv/applictn.h tv/codepage.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/parttree.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/screen.h\
	tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
obj/dskclose.o:: $(DEPS_18)
	$(RHIDE_COMPILE.cc.o)
DEPS_19=dskedito.cc ced_clas.h ced_exte.h ced_pcre.h ceditint.h ceditor.h\
	compatlayer.h configed.h dskedito.cc dskedito.h dskwin.h edcollec.h\
	pmcoll.h sarray.h setapp.h setstack.h settvuti.h sindicat.h\
	tnocastc.h tstringa.h tv.h tv/app.h tv/applictn.h tv/codepage.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/parttree.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/screen.h\
	tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
obj/dskedito.o:: $(DEPS_19)
	$(RHIDE_COMPILE.cc.o)
DEPS_20=dskhelp.cc ced_clas.h ced_exte.h ced_pcre.h ceditint.h ceditor.h\
	compatlayer.h configed.h dskhelp.cc dskhelp.h dskwin.h edcollec.h\
	inf.h infbase.h infbaser.h infr.h pmcoll.h sarray.h setapp.h\
	setstack.h settvuti.h sindicat.h tnocastc.h tstringa.h tv.h\
	tv/app.h tv/applictn.h tv/codepage.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h tv/listbox.h\
	tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/parttree.h tv/point.h tv/program.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/screen.h tv/scrlbar.h\
	tv/scroller.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
obj/dskhelp.o:: $(DEPS_20)
	$(RHIDE_COMPILE.cc.o)
DEPS_21=dskman.cc ceditint.h compatlayer.h configed.h dskman.cc dskman.h\
	dskwin.h manview.h rhutils.h setapp.h tv.h tv/app.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/scroller.h tv/stddlg.h\
	tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h
obj/dskman.o:: $(DEPS_21)
	$(RHIDE_COMPILE.cc.o)
DEPS_22=dskmessa.cc ceditint.h ceditor.h compatlayer.h configed.h\
	dskmessa.cc dskmessa.h dskwin.h edmsg.h setapp.h settvuti.h tv.h\
	tv/app.h tv/applictn.h tv/codepage.h tv/configtv.h tv/desktop.h\
	tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/object.h tv/objects.h tv/opstream.h\
	tv/parttree.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/screen.h tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h
obj/dskmessa.o:: $(DEPS_22)
	$(RHIDE_COMPILE.cc.o)
DEPS_23=dskmp3.cc ceditint.h ceditor.h compatlayer.h configed.h dskmp3.cc\
	dskmp3.h dskwin.h intermp3.h mixer.h setapp.h settvuti.h tv.h\
	tv/app.h tv/configtv.h tv/desktop.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h
obj/dskmp3.o:: $(DEPS_23)
	$(RHIDE_COMPILE.cc.o)
DEPS_24=dskwin.cc ceditor.h compatlayer.h dskwin.cc dskwin.h setapp.h\
	settvuti.h tv.h tv/app.h tv/configtv.h tv/desktop.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/intl.h tv/ipstream.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/program.h tv/pstream.h\
	tv/rect.h tv/stddlg.h tv/streambl.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h
obj/dskwin.o:: $(DEPS_24)
	$(RHIDE_COMPILE.cc.o)
DEPS_25=dstfile.cc ced_clas.h ced_exte.h ced_inte.h ced_pcre.h ceditint.h\
	ceditor.h codepage.h compatlayer.h configed.h dktclock.h dskclip.h\
	dskhelp.h dskwin.h dstfile.cc edcollec.h edhists.h edmsg.h\
	edprint.h edspecs.h fileopen.h fiopeaid.h inf.h infbase.h\
	infbaser.h infr.h mixer.h pathlist.h pathtool.h pmcoll.h sarray.h\
	setapp.h setstack.h settvuti.h sindicat.h ssyntax.h tags.h\
	tnocastc.h tpaltext.h tstringa.h tv.h tv/app.h tv/applictn.h\
	tv/codepage.h tv/collectn.h tv/configfile.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/filecoll.h tv/fontcoll.h tv/fpbase.h tv/fpstream.h tv/gkey.h\
	tv/group.h tv/indicato.h tv/intl.h tv/iopstrm.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/palette.h\
	tv/parttree.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/screen.h tv/scrlbar.h tv/scroller.h tv/searchrc.h\
	tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/strmblcl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
obj/dstfile.o:: $(DEPS_25)
	$(RHIDE_COMPILE.cc.o)
DEPS_26=dumpfile.cc compatlayer.h dumpfile.cc edmsg.h tv.h tv/configtv.h\
	tv/intl.h tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h\
	tv/views.h
obj/dumpfile.o:: $(DEPS_26)
	$(RHIDE_COMPILE.cc.o)
DEPS_27=
.PHONY: easydiag.gpr.force
all:: easydiag.gpr.force
easydiag.gpr.force:
	$(MAKE) -f easydiag.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_28=edcolor.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h compatlayer.h\
	diaghelp.h easydia1.h easydiag.h edcolor.cc pal.h palbcc.h\
	palconv.h paldjd.h palfte.h palmc.h pmcoll.h sarray.h setapp.h\
	setstack.h settvuti.h sindicat.h tnocastc.h tsbutton.h tslistbo.h\
	tssortva.h tstringa.h tstrlbox.h tstsorlb.h tsview.h tsviewco.h\
	tv.h tv/app.h tv/button.h tv/clrdlg.h tv/clrgroup.h tv/clritem.h\
	tv/collectn.h tv/colorsel.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/indicato.h\
	tv/intl.h tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/palette.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
obj/edcolor.o:: $(DEPS_28)
	$(RHIDE_COMPILE.cc.o)
DEPS_29=edconst.cc ced_coma.h ced_exte.h ced_inte.h ced_pcre.h ceditor.h\
	compatlayer.h dskwin.h edconst.cc editcoma.h inf.h infbase.h\
	infbaser.h infr.h setapp.h setstack.h settvuti.h tinppipe.h\
	tnocastc.h tv.h tv/collectn.h tv/configtv.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/scroller.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
obj/edconst.o:: $(DEPS_29)
	$(RHIDE_COMPILE.cc.o)
DEPS_30=edfonts.cc compatlayer.h edfonts.cc setapp.h tv.h tv/app.h\
	tv/applictn.h tv/codepage.h tv/collectn.h tv/configtv.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/fontcoll.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/parttree.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/screen.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/yes_mss.h
obj/edfonts.o:: $(DEPS_30)
	$(RHIDE_COMPILE.cc.o)
DEPS_31=editdiag.cc advice.h ced_inte.h ceditint.h ceditor.h compatlayer.h\
	configed.h easydia1.h easydiag.h editdiag.cc edspecs.h setapp.h\
	setstack.h settvuti.h tnocastc.h tsbutton.h tschkbox.h tstatext.h\
	tstextsc.h tsvegrp.h tsview.h tsviewco.h ttextscr.h tv.h tv/app.h\
	tv/applictn.h tv/button.h tv/checkbox.h tv/cluster.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/intl.h tv/ipstream.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/palette.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/screen.h tv/scrlbar.h tv/scroller.h tv/sitem.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h vername.h
obj/editdiag.o:: $(DEPS_31)
	$(RHIDE_COMPILE.cc.o)
DEPS_32=editmain.cc advice.h bufun.h ced_clas.h ced_coma.h ced_exte.h\
	ced_inte.h ced_pcre.h ceditint.h ceditor.h compatlayer.h configed.h\
	datetools.h debug.h diaghelp.h dktclock.h dskclose.h dskedito.h\
	dskhelp.h dskman.h dskwin.h edcollec.h edhists.h editmain.cc\
	edmsg.h edprint.h edspecs.h fileopen.h fiopeaid.h inf.h infbase.h\
	infbaser.h infr.h intermp3.h loadcle.h loadkbin.h loadnobkp.h\
	loadshl.h mixer.h pal.h pathlist.h pathtool.h pmcoll.h rhutils.h\
	runprog.h sarray.h sdginter.h setapp.h setstack.h settvuti.h\
	sindicat.h splinman.h ssyntax.h stackdbg.h tags.h tnocastc.h\
	tnosostr.h tpaltext.h tprogdia.h tstringa.h tv.h tv/app.h\
	tv/applictn.h tv/calc.h tv/chdirdlg.h tv/cmdset.h tv/codepage.h\
	tv/collectn.h tv/configfile.h tv/configtv.h tv/desktop.h\
	tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h tv/filecoll.h\
	tv/filedlg.h tv/gkey.h tv/group.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/menubar.h tv/menuitem.h\
	tv/menus.h tv/menuview.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/palette.h\
	tv/parttree.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/screen.h tv/scrlbar.h tv/scroller.h tv/searchrc.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h\
	tv/submenu.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
obj/editmain.o:: $(DEPS_32)
	$(RHIDE_COMPILE.cc.o)
DEPS_33=editmenu.cc ced_clas.h ced_coma.h ced_exte.h ced_pcre.h ceditint.h\
	ceditor.h compatlayer.h configed.h editcoma.h editmenu.cc inf.h\
	infbase.h infbaser.h infr.h pmcoll.h sarray.h setapp.h setconst.h\
	setstack.h settvuti.h sindicat.h tinppipe.h tnocastc.h tstringa.h\
	tv.h tv/app.h tv/applictn.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/filedlg.h tv/group.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/menubar.h tv/menuitem.h\
	tv/menus.h tv/menuview.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/program.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/screen.h tv/scrlbar.h tv/scroller.h tv/sortcoll.h tv/sortlibo.h\
	tv/statsdef.h tv/statsitm.h tv/statslin.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/submenu.h tv/system.h tv/tkeys.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/editmenu.o:: $(DEPS_33)
	$(RHIDE_COMPILE.cc.o)
DEPS_34=editorfo.cc ced_clas.h ced_exte.h ced_inte.h ced_pcre.h ceditint.h\
	ceditor.h compatlayer.h configed.h editorfo.cc pmcoll.h sarray.h\
	setstack.h settvuti.h sindicat.h tnocastc.h tstringa.h tv.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/editorfo.o:: $(DEPS_34)
	$(RHIDE_COMPILE.cc.o)
DEPS_35=editpale.cc compatlayer.h configed.h editpale.cc setapp.h\
	tpaltext.h tv.h tv/button.h tv/clrselct.h tv/cluster.h\
	tv/colorsel.h tv/configtv.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/intl.h tv/ipstream.h tv/label.h\
	tv/msgbox.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/radiobtn.h tv/rect.h tv/screen.h tv/scrlbar.h\
	tv/sitem.h tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h\
	tv/tkeyext.h tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h
obj/editpale.o:: $(DEPS_35)
	$(RHIDE_COMPILE.cc.o)
DEPS_36=editwind.cc ced_clas.h ced_coma.h ced_exte.h ced_pcre.h ceditint.h\
	ceditor.h compatlayer.h configed.h editwind.cc pmcoll.h sarray.h\
	setstack.h settvuti.h sindicat.h tnocastc.h tstringa.h tv.h\
	tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h tv/frame.h\
	tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/palette.h tv/point.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/screen.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strmblcl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/editwind.o:: $(DEPS_36)
	$(RHIDE_COMPILE.cc.o)
DEPS_37=edkeys.cc ced_coma.h ced_inte.h ceditint.h ceditor.h compatlayer.h\
	configed.h diaghelp.h dyncat.h easydia1.h easydiag.h edhists.h\
	editcoma.h edkeys.cc edmsg.h inputsca.h keytrans.h loadkbin.h mli.h\
	mlieditd.h setapp.h setstack.h settvuti.h tdiagaid.h tdiagrow.h\
	tnocastc.h tsbutton.h tsinplin.h tslabel.h tstatext.h tstringa.h\
	tstrlbox.h tsvegrp.h tsview.h tsviewco.h tv.h tv/app.h tv/button.h\
	tv/cluster.h tv/codepage.h tv/collectn.h tv/configtv.h tv/desktop.h\
	tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h tv/filedlg.h\
	tv/gkey.h tv/group.h tv/history.h tv/inputln.h tv/intl.h\
	tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/parttree.h tv/point.h tv/program.h tv/pstream.h\
	tv/radiobtn.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sitem.h\
	tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/sttctext.h tv/system.h tv/tkeyext.h tv/tkeys.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h
obj/edkeys.o:: $(DEPS_37)
	$(RHIDE_COMPILE.cc.o)
DEPS_38=edmsg.cc ced_clas.h ced_coma.h ced_exte.h ced_pcre.h ceditint.h\
	ceditor.h codepage.h compatlayer.h configed.h dskmessa.h dskwin.h\
	edhists.h editcoma.h edmsg.cc edmsg.h fileopen.h fiopeaid.h\
	pmcoll.h sarray.h setapp.h setstack.h settvuti.h sindicat.h\
	splinman.h tnocastc.h tstringa.h tv.h tv/app.h tv/applictn.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/indicato.h\
	tv/intl.h tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/osclipboard.h tv/parttree.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/screen.h\
	tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
obj/edmsg.o:: $(DEPS_38)
	$(RHIDE_COMPILE.cc.o)
DEPS_39=edprefs.cc advice.h ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	codepage.h compatlayer.h diaghelp.h dktclock.h easydia1.h\
	easydiag.h edcollec.h edmsg.h edprefs.cc edspecs.h pmcoll.h\
	sarray.h setapp.h setstack.h settvuti.h sindicat.h tnocastc.h\
	tsbutton.h tschkbox.h tshzgrp.h tsinplin.h tslabel.h tslistbo.h\
	tsradbot.h tssortlb.h tssortva.h tstatext.h tstringa.h tsvegrp.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/applictn.h tv/button.h\
	tv/checkbox.h tv/cluster.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/filecoll.h tv/fontcoll.h tv/fpbase.h tv/fpstream.h\
	tv/group.h tv/history.h tv/indicato.h tv/inputln.h tv/intl.h\
	tv/iopstrm.h tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/parttree.h tv/point.h tv/program.h\
	tv/pstream.h tv/radiobtn.h tv/rect.h tv/resource.h tv/screen.h\
	tv/scrlbar.h tv/searchrc.h tv/sitem.h tv/sortcoll.h tv/sortlibo.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/edprefs.o:: $(DEPS_39)
	$(RHIDE_COMPILE.cc.o)
DEPS_40=edprint.cc ceditint.h compatlayer.h configed.h easydia1.h\
	easydiag.h edmsg.h edprint.cc setapp.h tsbutton.h tschkbox.h\
	tshzgrp.h tsinplin.h tslabel.h tsradbot.h tsview.h tsviewco.h tv.h\
	tv/app.h tv/button.h tv/checkbox.h tv/cluster.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/fpbase.h tv/fpstream.h tv/group.h tv/history.h tv/inputln.h\
	tv/intl.h tv/iopstrm.h tv/ipstream.h tv/label.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/radiobtn.h tv/rect.h tv/sitem.h\
	tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
obj/edprint.o:: $(DEPS_40)
	$(RHIDE_COMPILE.cc.o)
DEPS_41=edprj.cc advice.h ced_clas.h ced_coma.h ced_exte.h ced_pcre.h\
	ceditint.h ceditor.h codepage.h compatlayer.h configed.h debug.h\
	dskprj.h dskwin.h edcollec.h edhists.h editcoma.h edprj.cc\
	edspecs.h fileopen.h fiopeaid.h pathtool.h pmcoll.h rhutils.h\
	sarray.h sdginter.h setapp.h setstack.h settvuti.h sindicat.h\
	tags.h tnocastc.h tstringa.h tv.h tv/app.h tv/applictn.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/filecoll.h tv/filedlg.h\
	tv/filelist.h tv/fpbase.h tv/fpstream.h tv/group.h tv/indicato.h\
	tv/intl.h tv/iopstrm.h tv/ipstream.h tv/listbox.h tv/lstviewr.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/parttree.h tv/point.h tv/program.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/screen.h tv/scrlbar.h\
	tv/searchrc.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h\
	tv/strmblcl.h tv/strncoll.h tv/system.h tv/tkeys.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/edprj.o:: $(DEPS_41)
	$(RHIDE_COMPILE.cc.o)
DEPS_42=edspecs.cc ced_inte.h compatlayer.h edspecs.cc edspecs.h pathtool.h\
	tv.h tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h\
	tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvutil.h tv/views.h
obj/edspecs.o:: $(DEPS_42)
	$(RHIDE_COMPILE.cc.o)
DEPS_43=
.PHONY: extra.gpr.force
all:: extra.gpr.force
extra.gpr.force:
	$(MAKE) -f extra.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_44=fstrcmp.c fstrcmp.c
obj/fstrcmp.o:: $(DEPS_44)
	$(RHIDE_COMPILE.c.o)
DEPS_45=getctxhl.cc ced_clas.h ced_coma.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskhelp.h dskwin.h editcoma.h fileopen.h getctxhl.cc\
	inf.h infbase.h infbaser.h infr.h pmcoll.h sarray.h setapp.h\
	setstack.h settvuti.h sindicat.h tnocastc.h tstringa.h tv.h\
	tv/app.h tv/applictn.h tv/codepage.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h tv/listbox.h\
	tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/parttree.h tv/point.h tv/program.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/screen.h tv/scrlbar.h\
	tv/scroller.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
obj/getctxhl.o:: $(DEPS_45)
	$(RHIDE_COMPILE.cc.o)
DEPS_46=gzfiles.cc ceditint.h compatlayer.h configed.h gzfiles.cc gzfiles.h\
	tv.h tv/configtv.h tv/intl.h tv/ipstream.h tv/msgbox.h\
	tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
obj/gzfiles.o:: $(DEPS_46)
	$(RHIDE_COMPILE.cc.o)
DEPS_47=holidays.cc ceditint.h compatlayer.h configed.h datetools.h\
	easydia1.h easydiag.h editcoma.h edspecs.h holidays.cc setapp.h\
	tsbutton.h tslabel.h tsradbot.h tsvegrp.h tsview.h tsviewco.h tv.h\
	tv/app.h tv/button.h tv/cluster.h tv/configtv.h tv/desktop.h\
	tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/intl.h tv/ipstream.h tv/label.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/program.h tv/pstream.h tv/radiobtn.h tv/rect.h tv/sitem.h\
	tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
obj/holidays.o:: $(DEPS_47)
	$(RHIDE_COMPILE.cc.o)
DEPS_48=
.PHONY: inffd.gpr.force
all:: inffd.gpr.force
inffd.gpr.force:
	$(MAKE) -f inffd.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_49=intgrep.cc ced_clas.h ced_exte.h ced_pcre.h ceditint.h ceditor.h\
	compatlayer.h configed.h dyncat.h edhists.h edmsg.h intgrep.cc\
	pathtool.h pmcoll.h rhutils.h sarray.h setapp.h setstack.h\
	settvuti.h sindicat.h splinman.h tinppipe.h tnocastc.h tstringa.h\
	tv.h tv/app.h tv/applictn.h tv/button.h tv/checkbox.h tv/cluster.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/fpbase.h tv/fpstream.h\
	tv/group.h tv/history.h tv/indicato.h tv/inputln.h tv/intl.h\
	tv/iopstrm.h tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/parttree.h tv/point.h tv/program.h\
	tv/pstream.h tv/radiobtn.h tv/rect.h tv/resource.h tv/screen.h\
	tv/scrlbar.h tv/sitem.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/intgrep.o:: $(DEPS_49)
	$(RHIDE_COMPILE.cc.o)
DEPS_50=keytrans.cc ced_coma.h ced_exte.h ceditor.h compatlayer.h dyncat.h\
	keytrans.cc keytrans.h setstack.h settvuti.h tnocastc.h tstringa.h\
	tv.h tv/codepage.h tv/collectn.h tv/configtv.h tv/event.h tv/gkey.h\
	tv/intl.h tv/ipstream.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/pstream.h tv/resource.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tkeyext.h tv/tkeys.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/views.h tv/yes_mss.h
obj/keytrans.o:: $(DEPS_50)
	$(RHIDE_COMPILE.cc.o)
DEPS_51=
.PHONY: librhuti.gpr.force
all:: librhuti.gpr.force
librhuti.gpr.force:
	$(MAKE) -f librhuti.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_52=linelen.cc ced_clas.h ceditor.h compatlayer.h linelen.cc settvuti.h\
	tv.h tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h\
	tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvutil.h tv/views.h
obj/linelen.o:: $(DEPS_52)
	$(RHIDE_COMPILE.cc.o)
DEPS_53=loadcle.cc ced_pcre.h ceditint.h compatlayer.h configed.h dyncat.h\
	loadcle.cc loadcle.h tv.h tv/collectn.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/pstream.h tv/resource.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h\
	tv/yes_mss.h
obj/loadcle.o:: $(DEPS_53)
	$(RHIDE_COMPILE.cc.o)
DEPS_54=loaddefl.cc ced_clas.h ced_exte.h ced_inte.h ced_pcre.h ceditor.h\
	compatlayer.h easydia1.h easydiag.h loaddefl.cc loadshl.h\
	pathtool.h pmcoll.h sarray.h setapp.h setstack.h settvuti.h\
	sindicat.h tdiagaid.h tdiagrow.h tnocastc.h tsbutton.h tshzgrp.h\
	tsinplin.h tslabel.h tslistbo.h tssortlb.h tssortva.h tstringa.h\
	tstrlbox.h tsview.h tsviewco.h tv.h tv/app.h tv/button.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h\
	tv/drawbuf.h tv/event.h tv/group.h tv/history.h tv/indicato.h\
	tv/inputln.h tv/intl.h tv/ipstream.h tv/label.h tv/listbox.h\
	tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/loaddefl.o:: $(DEPS_54)
	$(RHIDE_COMPILE.cc.o)
DEPS_55=loadfunc.cc compatlayer.h loadfunc.cc pathtool.h tv.h tv/codepage.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h tv/parttree.h\
	tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvutil.h tv/views.h
obj/loadfunc.o:: $(DEPS_55)
	$(RHIDE_COMPILE.cc.o)
DEPS_56=loadnobkp.cc ced_exte.h ced_pcre.h ceditint.h ceditor.h\
	compatlayer.h configed.h easydia1.h easydiag.h loadnobkp.cc\
	loadnobkp.h loadshl.h setapp.h setstack.h settvuti.h tdiagaid.h\
	tdiagrow.h tnocastc.h tsbutton.h tsinplin.h tslabel.h tstringa.h\
	tstrlbox.h tsview.h tsviewco.h tv.h tv/app.h tv/button.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h\
	tv/drawbuf.h tv/group.h tv/history.h tv/inputln.h tv/intl.h\
	tv/ipstream.h tv/label.h tv/lstviewr.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/loadnobkp.o:: $(DEPS_56)
	$(RHIDE_COMPILE.cc.o)
DEPS_57=loadshl.cc ced_clas.h ced_exte.h ced_inte.h ced_pcre.h ceditint.h\
	ceditor.h compatlayer.h configed.h dyncat.h loadshl.cc loadshl.h\
	pmcoll.h sarray.h setstack.h settvuti.h sindicat.h tnocastc.h\
	tstringa.h tv.h tv/codepage.h tv/collectn.h tv/configtv.h\
	tv/drawbuf.h tv/event.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/parttree.h tv/point.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
obj/loadshl.o:: $(DEPS_57)
	$(RHIDE_COMPILE.cc.o)
DEPS_58=loadusew.cc ced_clas.h ced_exte.h ced_inte.h ced_pcre.h ceditor.h\
	compatlayer.h easydia1.h easydiag.h loadshl.h loadusew.cc\
	pathtool.h pmcoll.h sarray.h setapp.h setstack.h settvuti.h\
	sindicat.h tdiagaid.h tdiagrow.h tnocastc.h tsbutton.h tshzgrp.h\
	tsinplin.h tslabel.h tslistbo.h tssortlb.h tssortva.h tstringa.h\
	tstrlbox.h tsview.h tsviewco.h tv.h tv/app.h tv/button.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h\
	tv/drawbuf.h tv/event.h tv/group.h tv/history.h tv/indicato.h\
	tv/inputln.h tv/intl.h tv/ipstream.h tv/label.h tv/listbox.h\
	tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/loadusew.o:: $(DEPS_58)
	$(RHIDE_COMPILE.cc.o)
DEPS_59=macrocom.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h macrocom.cc pmcoll.h sarray.h setapp.h setstack.h\
	settvuti.h sindicat.h slpinter.h tnocastc.h tstringa.h tv.h\
	tv/app.h tv/applictn.h tv/collectn.h tv/configtv.h tv/desktop.h\
	tv/drawbuf.h tv/event.h tv/group.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/program.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/macrocom.o:: $(DEPS_59)
	$(RHIDE_COMPILE.cc.o)
DEPS_60=menuload.cc ced_clas.h ced_coma.h ced_exte.h ced_pcre.h ceditint.h\
	ceditor.h compatlayer.h configed.h dyncat.h keytrans.h menuload.cc\
	mli.h mlieditd.h pmcoll.h sarray.h setapp.h setstack.h settvuti.h\
	sindicat.h tnocastc.h tstringa.h tv.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/drawbuf.h tv/event.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/menu.h tv/menubar.h tv/menuitem.h tv/menus.h\
	tv/menuview.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/parttree.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h\
	tv/statsdef.h tv/statsitm.h tv/statslin.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/submenu.h tv/system.h tv/tkeys.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/menuload.o:: $(DEPS_60)
	$(RHIDE_COMPILE.cc.o)
DEPS_61=mli.cc ced_pcre.h compatlayer.h configed.h dyncat.h loadshl.h\
	mli.cc mli.h mliabase.h mliasimp.h mlibase.h mlivar.h pathtool.h\
	tv.h tv/codepage.h tv/configtv.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/opstream.h\
	tv/parttree.h tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h\
	tv/yes_mss.h
obj/mli.o:: $(DEPS_61)
	$(RHIDE_COMPILE.cc.o)
DEPS_62=mliasimp.cc mli.h mliabase.h mliasimp.cc mliasimp.h mlivar.h
obj/mliasimp.o:: $(DEPS_62)
	$(RHIDE_COMPILE.cc.o)
DEPS_63=mlicsdg.cc compatlayer.h mli.h mliabase.h mlibase.h mlicsdg.cc\
	mlicsdg.h mlisdg.h mlisdgi.h mlivar.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h\
	tv/yes_mss.h ucdefs.h
obj/mlicsdg.o:: $(DEPS_63)
	$(RHIDE_COMPILE.cc.o)
DEPS_64=mliediti.cc compatlayer.h edmsg.h mli.h mliabase.h mliasimp.h\
	mlibase.h mlieditd.h mliediti.cc mliedito.h mlivar.h settvuti.h\
	tnocastc.h tv.h tv/collectn.h tv/configtv.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/pstream.h tv/resource.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h tv/yes_mss.h\
	tvsetuti.h
obj/mliediti.o:: $(DEPS_64)
	$(RHIDE_COMPILE.cc.o)
DEPS_65=mliedito.cc ced_coma.h ceditor.h compatlayer.h dyncat.h edmsg.h\
	keytrans.h mli.h mliabase.h mlibase.h mlieditd.h mliedito.cc\
	mliedito.h mlisdg.h mlisdgi.h mlivar.h rhutils.h runprog.h\
	settvuti.h tnocastc.h tstringa.h tv.h tv/collectn.h tv/configtv.h\
	tv/intl.h tv/ipstream.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/pstream.h\
	tv/resource.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/views.h tv/yes_mss.h tvsetuti.h
obj/mliedito.o:: $(DEPS_65)
	$(RHIDE_COMPILE.cc.o)
DEPS_66=mlisdg.cc compatlayer.h mli.h mliabase.h mliasimp.h mlibase.h\
	mlicsdg.h mlisdg.cc mlisdg.h mlisdgi.h mlivar.h tv.h tv/configtv.h\
	tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/views.h tv/yes_mss.h
obj/mlisdg.o:: $(DEPS_66)
	$(RHIDE_COMPILE.cc.o)
DEPS_67=msignal.cc ced_inte.h ceditint.h compatlayer.h configed.h\
	msignal.cc stackdbg.h tv.h tv/configtv.h tv/event.h tv/eventqu.h\
	tv/intl.h tv/ipstream.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/screen.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
obj/msignal.o:: $(DEPS_67)
	$(RHIDE_COMPILE.cc.o)
DEPS_68=nceditor.cc compatlayer.h nceditor.cc tv/configtv.h tv/tvutil.h
obj/nceditor.o:: $(DEPS_68)
	$(RHIDE_COMPILE.cc.o)
DEPS_69=ndskwasc.cc compatlayer.h ndskwasc.cc tv/configtv.h tv/tvutil.h
obj/ndskwasc.o:: $(DEPS_69)
	$(RHIDE_COMPILE.cc.o)
DEPS_70=ndskwcal.cc compatlayer.h ndskwcal.cc tv/configtv.h tv/tvutil.h
obj/ndskwcal.o:: $(DEPS_70)
	$(RHIDE_COMPILE.cc.o)
DEPS_71=ndskwcli.cc compatlayer.h ndskwcli.cc tv/configtv.h tv/tvutil.h
obj/ndskwcli.o:: $(DEPS_71)
	$(RHIDE_COMPILE.cc.o)
DEPS_72=ndskwclo.cc compatlayer.h ndskwclo.cc tv/configtv.h tv/tvutil.h
obj/ndskwclo.o:: $(DEPS_72)
	$(RHIDE_COMPILE.cc.o)
DEPS_73=ndskwedi.cc compatlayer.h ndskwedi.cc tv/configtv.h tv/tvutil.h
obj/ndskwedi.o:: $(DEPS_73)
	$(RHIDE_COMPILE.cc.o)
DEPS_74=ndskwhel.cc compatlayer.h ndskwhel.cc tv/configtv.h tv/tvutil.h
obj/ndskwhel.o:: $(DEPS_74)
	$(RHIDE_COMPILE.cc.o)
DEPS_75=ndskwman.cc compatlayer.h ndskwman.cc tv/configtv.h tv/tvutil.h
obj/ndskwman.o:: $(DEPS_75)
	$(RHIDE_COMPILE.cc.o)
DEPS_76=ndskwmes.cc compatlayer.h ndskwmes.cc tv/configtv.h tv/tvutil.h
obj/ndskwmes.o:: $(DEPS_76)
	$(RHIDE_COMPILE.cc.o)
DEPS_77=ndskwmp3.cc compatlayer.h ndskwmp3.cc tv/configtv.h tv/tvutil.h
obj/ndskwmp3.o:: $(DEPS_77)
	$(RHIDE_COMPILE.cc.o)
DEPS_78=ndskwprj.cc compatlayer.h ndskwprj.cc tv/configtv.h tv/tvutil.h
obj/ndskwprj.o:: $(DEPS_78)
	$(RHIDE_COMPILE.cc.o)
DEPS_79=neditwin.cc compatlayer.h neditwin.cc tv/configtv.h tv/tvutil.h
obj/neditwin.o:: $(DEPS_79)
	$(RHIDE_COMPILE.cc.o)
DEPS_80=nfileedi.cc compatlayer.h nfileedi.cc tv/configtv.h tv/tvutil.h
obj/nfileedi.o:: $(DEPS_80)
	$(RHIDE_COMPILE.cc.o)
DEPS_81=nsindica.cc compatlayer.h nsindica.cc tv/configtv.h tv/tvutil.h
obj/nsindica.o:: $(DEPS_81)
	$(RHIDE_COMPILE.cc.o)
DEPS_82=ntedcol.cc ntedcol.cc tvsetuti.h
obj/ntedcol.o:: $(DEPS_82)
	$(RHIDE_COMPILE.cc.o)
DEPS_83=parser.c compatlayer.h parser.c tv/configtv.h
obj/parser.o:: $(DEPS_83)
	$(RHIDE_COMPILE.c.o)
DEPS_84=pathlist.cc ceditint.h compatlayer.h configed.h easydia1.h\
	easydiag.h pathlist.cc pathlist.h rhutils.h setapp.h settvuti.h\
	tdiagaid.h tdiagrow.h tsbutton.h tsinplin.h tslabel.h tstringa.h\
	tstrlbox.h tsview.h tsviewco.h tv.h tv/app.h tv/button.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h\
	tv/drawbuf.h tv/fpbase.h tv/fpstream.h tv/group.h tv/history.h\
	tv/inputln.h tv/intl.h tv/iopstrm.h tv/ipstream.h tv/label.h\
	tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/screen.h tv/scrlbar.h tv/stddlg.h tv/streambl.h tv/strmblcl.h\
	tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h
obj/pathlist.o:: $(DEPS_84)
	$(RHIDE_COMPILE.cc.o)
DEPS_85=pathtool.cc ceditint.h compatlayer.h configed.h pathlist.h\
	pathtool.cc pathtool.h rhutils.h setapp.h settvuti.h tnocastc.h\
	tv.h tv/collectn.h tv/configtv.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/pstream.h tv/resource.h tv/screen.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h\
	tv/yes_mss.h tvsetuti.h
obj/pathtool.o:: $(DEPS_85)
	$(RHIDE_COMPILE.cc.o)
DEPS_86=pclipper.cc bufun.h compatlayer.h pclipper.cc tv.h tv/codepage.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h tv/parttree.h\
	tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvutil.h tv/views.h
obj/pclipper.o:: $(DEPS_86)
	$(RHIDE_COMPILE.cc.o)
DEPS_87=pmacros.cc ceditor.h compatlayer.h pmacros.cc pmcoll.h settvuti.h\
	tstringa.h tv.h tv/collectn.h tv/configtv.h tv/intl.h tv/ipstream.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/pstream.h tv/resource.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h\
	tv/yes_mss.h
obj/pmacros.o:: $(DEPS_87)
	$(RHIDE_COMPILE.cc.o)
DEPS_88=pperl.cc bufun.h pperl.cc
obj/pperl.o:: $(DEPS_88)
	$(RHIDE_COMPILE.cc.o)
DEPS_89=pphp.cc bufun.h pphp.cc
obj/pphp.o:: $(DEPS_89)
	$(RHIDE_COMPILE.cc.o)
DEPS_90=ppython.cc bufun.h compatlayer.h ppython.cc tv.h tv/configtv.h\
	tv/intl.h tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h\
	tv/views.h
obj/ppython.o:: $(DEPS_90)
	$(RHIDE_COMPILE.cc.o)
DEPS_91=pvarious.cc bufun.h compatlayer.h pvarious.cc tv.h tv/codepage.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h tv/parttree.h\
	tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvutil.h tv/views.h
obj/pvarious.o:: $(DEPS_91)
	$(RHIDE_COMPILE.cc.o)
DEPS_92=pvhdl.cc bufun.h compatlayer.h pvhdl.cc tv/configtv.h
obj/pvhdl.o:: $(DEPS_92)
	$(RHIDE_COMPILE.cc.o)
DEPS_93=runprog.cc ced_pcre.h ceditint.h ceditor.h compatlayer.h configed.h\
	dyncat.h easydia1.h easydiag.h edhists.h edmsg.h intermp3.h\
	loadcle.h rhutils.h runprog.cc runprog.h setapp.h setstack.h\
	settvuti.h splinman.h tsbutton.h tsinplin.h tslabel.h tslistbo.h\
	tssortlb.h tssortva.h tsvegrp.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/applictn.h tv/button.h tv/codepage.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/fpbase.h tv/fpstream.h tv/group.h tv/history.h tv/inputln.h\
	tv/intl.h tv/iopstrm.h tv/ipstream.h tv/label.h tv/listbox.h\
	tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/parttree.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/screen.h\
	tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h
obj/runprog.o:: $(DEPS_93)
	$(RHIDE_COMPILE.cc.o)
DEPS_94=sceditor.cc ced_clas.h ced_exte.h ced_pcre.h ceditint.h ceditor.h\
	compatlayer.h configed.h pmcoll.h sarray.h sceditor.cc setstack.h\
	settvuti.h sindicat.h tnocastc.h tstringa.h tv.h tv/collectn.h\
	tv/configtv.h tv/drawbuf.h tv/event.h tv/group.h tv/indicato.h\
	tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/sceditor.o:: $(DEPS_94)
	$(RHIDE_COMPILE.cc.o)
DEPS_95=scresave.cc ced_clas.h ced_exte.h ced_pcre.h ceditint.h ceditor.h\
	compatlayer.h configed.h dyncat.h intermp3.h pathtool.h pmcoll.h\
	rhutils.h runprog.h sarray.h scresave.cc setapp.h setstack.h\
	settvuti.h sindicat.h tnocastc.h tstringa.h tv.h tv/app.h\
	tv/applictn.h tv/codepage.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/drawbuf.h tv/event.h tv/eventqu.h tv/gkey.h\
	tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/parttree.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/screen.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/scresave.o:: $(DEPS_95)
	$(RHIDE_COMPILE.cc.o)
DEPS_96=sdginter.cc ceditint.h compatlayer.h configed.h edmsg.h mli.h\
	mlisdgi.h sdginter.cc setapp.h tv.h tv/button.h tv/checkbox.h\
	tv/cluster.h tv/configtv.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/fpbase.h tv/fpstream.h tv/group.h tv/inputln.h tv/intl.h\
	tv/iopstrm.h tv/ipstream.h tv/label.h tv/msgbox.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/sitem.h tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h txhgen.h
obj/sdginter.o:: $(DEPS_96)
	$(RHIDE_COMPILE.cc.o)
DEPS_97=sdskasci.cc compatlayer.h dskascii.h dskwin.h streams/sdskasci.cc\
	tv.h tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h\
	tv/pstream.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
obj/sdskasci.o:: $(DEPS_97)
	$(RHIDE_COMPILE.cc.o)
DEPS_98=sdskcale.cc compatlayer.h dskcalen.h dskwin.h streams/sdskcale.cc\
	tv.h tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h\
	tv/pstream.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
obj/sdskcale.o:: $(DEPS_98)
	$(RHIDE_COMPILE.cc.o)
DEPS_99=sdskclip.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskclip.h dskwin.h pmcoll.h sarray.h setstack.h\
	settvuti.h sindicat.h streams/sdskclip.cc tnocastc.h tstringa.h\
	tv.h tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/sdskclip.o:: $(DEPS_99)
	$(RHIDE_COMPILE.cc.o)
DEPS_100=sdskclos.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskclose.h dskwin.h pmcoll.h sarray.h setstack.h\
	settvuti.h sindicat.h streams/sdskclos.cc tnocastc.h tstringa.h\
	tv.h tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/sdskclos.o:: $(DEPS_100)
	$(RHIDE_COMPILE.cc.o)
DEPS_101=sdskedit.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskedito.h dskwin.h pmcoll.h sarray.h setstack.h\
	settvuti.h sindicat.h streams/sdskedit.cc tnocastc.h tstringa.h\
	tv.h tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/sdskedit.o:: $(DEPS_101)
	$(RHIDE_COMPILE.cc.o)
DEPS_102=sdskhelp.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskhelp.h dskwin.h inf.h infbase.h infbaser.h infr.h\
	pmcoll.h sarray.h setstack.h settvuti.h sindicat.h\
	streams/sdskhelp.cc tnocastc.h tstringa.h tv.h tv/collectn.h\
	tv/configtv.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h tv/listbox.h\
	tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/scrlbar.h tv/scroller.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/sdskhelp.o:: $(DEPS_102)
	$(RHIDE_COMPILE.cc.o)
DEPS_103=sdskman.cc compatlayer.h dskman.h dskwin.h streams/sdskman.cc tv.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h tv/pstream.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
obj/sdskman.o:: $(DEPS_103)
	$(RHIDE_COMPILE.cc.o)
DEPS_104=sdskmess.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskmessa.h dskwin.h pmcoll.h sarray.h setstack.h\
	settvuti.h sindicat.h streams/sdskmess.cc tnocastc.h tstringa.h\
	tv.h tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/sdskmess.o:: $(DEPS_104)
	$(RHIDE_COMPILE.cc.o)
DEPS_105=sdskmp3.cc compatlayer.h dskmp3.h dskwin.h streams/sdskmp3.cc tv.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h tv/pstream.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
obj/sdskmp3.o:: $(DEPS_105)
	$(RHIDE_COMPILE.cc.o)
DEPS_106=sdskprj.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskprj.h dskwin.h pmcoll.h sarray.h setstack.h\
	settvuti.h sindicat.h streams/sdskprj.cc tnocastc.h tstringa.h tv.h\
	tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/sdskprj.o:: $(DEPS_106)
	$(RHIDE_COMPILE.cc.o)
DEPS_107=search.cc ced_clas.h ced_exte.h ced_inte.h ced_pcre.h ceditint.h\
	ceditor.h compatlayer.h configed.h pmcoll.h sarray.h search.cc\
	setstack.h settvuti.h sindicat.h tnocastc.h tstringa.h tv.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/parttree.h tv/point.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/search.o:: $(DEPS_107)
	$(RHIDE_COMPILE.cc.o)
DEPS_108=sedcolle.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskwin.h edcollec.h pmcoll.h sarray.h setstack.h\
	settvuti.h sindicat.h streams/sedcolle.cc tnocastc.h tstringa.h\
	tv.h tv/collectn.h tv/configtv.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/sedcolle.o:: $(DEPS_108)
	$(RHIDE_COMPILE.cc.o)
DEPS_109=
.PHONY: settv.gpr.force
all:: settv.gpr.force
settv.gpr.force:
	$(MAKE) -f settv.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_110=slpinter.cc ced_clas.h ced_coma.h ced_exte.h ced_inte.h ced_pcre.h\
	ceditint.h ceditor.h compatlayer.h completi.h configed.h dyncat.h\
	easydia1.h easydiag.h edhists.h edmsg.h keytrans.h mli.h mliabase.h\
	mlibase.h mlieditd.h mliedito.h mlivar.h pmcoll.h sarray.h setapp.h\
	setstack.h settvuti.h sindicat.h slpinter.cc slpinter.h tinppipe.h\
	tnocastc.h tsbutton.h tsinplpi.h tslabel.h tstringa.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/button.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/history.h tv/indicato.h tv/inputln.h tv/intl.h\
	tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
obj/slpinter.o:: $(DEPS_110)
	$(RHIDE_COMPILE.cc.o)
DEPS_111=splinman.cc ced_clas.h ced_exte.h ced_inte.h ced_pcre.h ceditor.h\
	compatlayer.h pmcoll.h sarray.h setstack.h settvuti.h sindicat.h\
	splinman.cc splinman.h tnocastc.h tstringa.h tv.h tv/collectn.h\
	tv/configtv.h tv/drawbuf.h tv/event.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
obj/splinman.o:: $(DEPS_111)
	$(RHIDE_COMPILE.cc.o)
DEPS_112=ssindica.cc ceditor.h compatlayer.h settvuti.h sindicat.h\
	ssindica.cc tv.h tv/configtv.h tv/drawbuf.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tvsetuti.h
obj/ssindica.o:: $(DEPS_112)
	$(RHIDE_COMPILE.cc.o)
DEPS_113=ssyntax.cc ceditint.h compatlayer.h configed.h easydia1.h\
	easydiag.h inf.h infbase.h infbaser.h infr.h setapp.h setstack.h\
	settvuti.h ssyntax.cc ssyntax.h tdiagaid.h tdiagrow.h tnocastc.h\
	tsbutton.h tsinplin.h tslabel.h tslistbo.h tssortva.h tstringa.h\
	tstrlbox.h tstsorlb.h tsvegrp.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/button.h tv/codepage.h tv/collectn.h tv/configtv.h tv/desktop.h\
	tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h tv/fpbase.h\
	tv/fpstream.h tv/group.h tv/history.h tv/inputln.h tv/intl.h\
	tv/iopstrm.h tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/parttree.h tv/point.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/scroller.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/sttctext.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
obj/ssyntax.o:: $(DEPS_113)
	$(RHIDE_COMPILE.cc.o)
DEPS_114=tags.cc advice.h ced_coma.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h completi.h easydia1.h easydiag.h edhists.h fileopen.h\
	fiopeaid.h pathtool.h rhutils.h setapp.h setstack.h settvuti.h\
	tags.cc tags.h tdiagaid.h tdiagrow.h tnocastc.h tsbutton.h\
	tshzgrp.h tslabel.h tslistbo.h tssortlb.h tssortva.h tstatext.h\
	tstringa.h tstrlbox.h tstsorlb.h tsvegrp.h tsview.h tsviewco.h tv.h\
	tv/app.h tv/applictn.h tv/button.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/fpbase.h tv/fpstream.h tv/group.h tv/intl.h tv/iopstrm.h\
	tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/screen.h tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h
obj/tags.o:: $(DEPS_114)
	$(RHIDE_COMPILE.cc.o)
DEPS_115=tedcolle.cc ced_clas.h ced_coma.h ced_exte.h ced_pcre.h ceditint.h\
	ceditor.h compatlayer.h configed.h dskclose.h dskedito.h dskwin.h\
	easydia1.h easydiag.h edcollec.h edspecs.h pmcoll.h sarray.h\
	setapp.h setstack.h settvuti.h sindicat.h tedcolle.cc tnocastc.h\
	tslistbo.h tssortlb.h tssortva.h tstringa.h tsview.h tsviewco.h\
	tv.h tv/app.h tv/applictn.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/parttree.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/screen.h\
	tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
obj/tedcolle.o:: $(DEPS_115)
	$(RHIDE_COMPILE.cc.o)
DEPS_116=tips.cc ceditint.h compatlayer.h configed.h easydia1.h easydiag.h\
	edmsg.h edspecs.h setapp.h tips.cc tsbutton.h tshzgrp.h tslabel.h\
	tsradbot.h tstextsc.h tsview.h tsviewco.h ttextscr.h tv.h tv/app.h\
	tv/applictn.h tv/button.h tv/cluster.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/label.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/palette.h tv/point.h tv/program.h tv/pstream.h tv/radiobtn.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/scroller.h tv/sitem.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h
obj/tips.o:: $(DEPS_116)
	$(RHIDE_COMPILE.cc.o)
DEPS_117=tpaltext.cc compatlayer.h tpaltext.cc tpaltext.h tv.h\
	tv/configtv.h tv/fpbase.h tv/fpstream.h tv/intl.h tv/iopstrm.h\
	tv/ipstream.h tv/opstream.h tv/pstream.h tv/screen.h tv/stddlg.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h\
	tv/views.h
obj/tpaltext.o:: $(DEPS_117)
	$(RHIDE_COMPILE.cc.o)
DEPS_118=tsindica.cc ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h pmcoll.h sarray.h setstack.h settvuti.h sindicat.h\
	tnocastc.h tsindica.cc tstringa.h tv.h tv/collectn.h tv/configtv.h\
	tv/drawbuf.h tv/event.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/screen.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strmblcl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
obj/tsindica.o:: $(DEPS_118)
	$(RHIDE_COMPILE.cc.o)
DEPS_119=txhgen.cc bufun.h compatlayer.h mli.h mlisdgi.h rhutils.h\
	setstack.h settvuti.h tnocastc.h tv.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/pstream.h tv/resource.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/views.h tv/yes_mss.h txhgen.cc txhgen.h
obj/txhgen.o:: $(DEPS_119)
	$(RHIDE_COMPILE.cc.o)
DEPS_120=winlistd.cc advice.h ced_clas.h ced_exte.h ced_pcre.h ceditor.h\
	compatlayer.h dskwin.h easydia1.h easydiag.h edcollec.h editcoma.h\
	pmcoll.h sarray.h setapp.h setstack.h settvuti.h sindicat.h\
	tnocastc.h tsbutton.h tshzgrp.h tslistbo.h tssortva.h tstringa.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/applictn.h tv/button.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/indicato.h\
	tv/intl.h tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/parttree.h tv/point.h tv/program.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/screen.h tv/scrlbar.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h\
	winlistd.cc
obj/winlistd.o:: $(DEPS_120)
	$(RHIDE_COMPILE.cc.o)
all:: editor.exe
