# This file is automatically generated by RHIDE 1.5
# created with the command:
# gpr2mak infview.gpr
vpath_src=../infview ../settvuti ../extra ../infview/names ../infview/streams ../mainsrc ../setedit
vpath %.c $(vpath_src)
vpath %.cc $(vpath_src)
vpath %.cpp $(vpath_src)
vpath %.C $(vpath_src)
vpath %.cxx $(vpath_src)
vpath %.s $(vpath_src)
vpath %.S $(vpath_src)
vpath %.p $(vpath_src)
vpath %.pas $(vpath_src)
vpath %.f $(vpath_src)
vpath %.for $(vpath_src)
vpath %.F $(vpath_src)
vpath %.fpp $(vpath_src)
vpath %.i $(vpath_src)
vpath %.ii $(vpath_src)
vpath %.m $(vpath_src)
vpath %.asm $(vpath_src)
vpath %.nsm $(vpath_src)
vpath_header=../include ../settvuti/include ../infview/include\
	$(TVISION_INC) ../extra ../librhuti $(SUPPORT_INC) ../easydiag\
	../setedit/include
vpath %.h $(vpath_header)
vpath %.hpp $(vpath_header)
vpath %.ha $(vpath_header)
vpath %.hd $(vpath_header)
vpath_obj=objinf
vpath %.o $(vpath_obj)
FLAGS_FOR_SUBPROJECTS=RHIDE_OS_="$(RHIDE_OS_)" CFLAGS="$(CFLAGS)"\
	CXXFLAGS="$(CXXFLAGS)" LDFLAGS="$(LDFLAGS)" CPPFLAGS="$(CPPFLAGS)"
RHIDE_OS=$(RHIDE_OS_)
ifeq ($(strip $(RHIDE_OS)),)
ifneq ($(strip $(DJDIR)),)
RHIDE_OS_:=DJGPP
else
RHIDE_OS_:=$(patsubst CYGWIN%,CYGWIN,$(shell uname))
endif
endif

INCLUDE_DIRS=../include ../settvuti/include ../infview/include\
	$(TVISION_INC) ../extra ../librhuti $(SUPPORT_INC) ../easydiag\
	../setedit/include
LIB_DIRS=$(RHIDE_OS_LIBS_PATH) -L.
C_DEBUG_FLAGS=
C_OPT_FLAGS=
C_WARN_FLAGS=
C_C_LANG_FLAGS=
C_CXX_LANG_FLAGS=
C_P_LANG_FLAGS=
C_FPC_LANG_FLAGS=
C_F_LANG_FLAGS=
C_ADA_LANG_FLAGS=
LIBS=
LD_EXTRA_FLAGS=
C_EXTRA_FLAGS=-DFOR_EDITOR -DNoEditorSpecific
LOCAL_OPT=$(subst ___~~~___, ,$(subst $(notdir $<)___,,$(filter $(notdir\
	$<)___%,$(LOCAL_OPTIONS))))

OBJFILES=objinf/dyncat.o objinf/fstrcmp.o objinf/gzfiles.o objinf/inf.o\
	objinf/infbase.o objinf/infdummy.o objinf/infmain.o\
	objinf/infmenu.o objinf/manview.o objinf/nhiscoll.o\
	objinf/ninfview.o objinf/ninfwind.o objinf/nmanwind.o objinf/sinf.o\
	objinf/sman.o objinf/strncpyz.o
ALL_OBJFILES=objinf/dyncat.o obj/lablchek.o obj/lablradi.o obj/snostate.o\
	obj/tcheck2.o obj/tmiclust.o obj/tsbutton.o obj/tschkarr.o\
	obj/tschkbox.o obj/tshscrol.o obj/tshzgrp.o obj/tsinplin.o\
	obj/tsinplpi.o obj/tslabel.o obj/tslider.o obj/tslistbo.o\
	obj/tsradbot.o obj/tssortlb.o obj/tssosslb.o obj/tstatext.o\
	obj/tstextsc.o obj/tstsorlb.o obj/tsvegrp.o obj/tsview.o\
	obj/tsviewco.o obj/ttextscr.o objinf/fstrcmp.o objinf/gzfiles.o\
	objinf/inf.o objinf/infbase.o objinf/infdummy.o objinf/infmain.o\
	objinf/infmenu.o obj/abstorel.o obj/back2sl.o obj/basename.o\
	obj/fexpand.o obj/io.o obj/specs.o obj/splitfn.o obj/stricat.o\
	obj/stridown.o obj/stridup.o obj/strifree.o objinf/manview.o\
	objinf/nhiscoll.o objinf/ninfview.o objinf/ninfwind.o\
	objinf/nmanwind.o obj/diaghelp.o obj/dktclock.o obj/fileopen.o\
	obj/fiopeaid.o obj/inputsca.o obj/ninputsc.o obj/nostatex.o\
	obj/nprogbar.o obj/nprogres.o obj/ntnocast.o obj/ntnosost.o\
	obj/setstack.o obj/sprogbar.o obj/sprogres.o obj/stnocast.o\
	obj/stnonost.o obj/tdiagaid.o obj/tdiagrow.o obj/tinppipe.o\
	obj/tnocastc.o obj/tnosostr.o obj/tprogbar.o obj/tprogdia.o\
	obj/tprogrdi.o obj/tprogres.o obj/tstrlbox.o obj/uisarray.o\
	obj/ussarray.o obj/viewplus.o objinf/sinf.o objinf/sman.o\
	objinf/strncpyz.o
LIBRARIES=libeasyd.a librhuti.a libsettv.a
SOURCE_NAME=$<
OUTFILE=$@
SPECIAL_CFLAGS=
SPECIAL_LDFLAGS=
PROG_ARGS=
SRC_DIRS=../infview ../settvuti ../extra ../infview/names\
	../infview/streams ../mainsrc ../setedit
WUC=
EDITORS=
MAIN_TARGET=infview.exe
PROJECT_ITEMS=dyncat.cc easydiag.gpr fstrcmp.c gzfiles.cc inf.cc infbase.cc\
	infdummy.cc infmain.cc infmenu.cc librhuti.gpr manview.cc\
	nhiscoll.cc ninfview.cc ninfwind.cc nmanwind.cc settv.gpr sinf.cc\
	sman.cc strncpyz.cc
DEFAULT_MASK=*
RHIDE_BIN_DIR=/usr/local/bin
PASCAL_TYPE=GPC
GET_HOME=$(HOME)
CLEAN_FILES=$(MAIN_TARGET) $(OBJFILES)
DEFAULT_GREP_MASK=*.[cfhmnps]*
RHIDE_ADA_BIND_FILE=$(addprefix _,$(setsuffix .c,$(OUTFILE)))
RHIDE_AR=ar
RHIDE_ARFLAGS=rcs
RHIDE_AS=$(RHIDE_GCC)
RHIDE_CO=$(shell co -q $(co_arg))
RHIDE_COMPILE.C.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.C.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.C.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.F.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.adb.o=$(RHIDE_COMPILE_ADA)
RHIDE_COMPILE.asm.o=$(RHIDE_COMPILE.nsm.o)
RHIDE_COMPILE.c.i=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.c.o=$(RHIDE_COMPILE_C)
RHIDE_COMPILE.c.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.cc.ii=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cc.o=$(RHIDE_COMPILE_CC)
RHIDE_COMPILE.cc.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cpp.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cpp.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cpp.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.cxx.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cxx.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cxx.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.f.o=$(RHIDE_COMPILE_FORTRAN)
RHIDE_COMPILE.for.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.fpp.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.i.s=$(RHIDE_COMPILE.c.s)
RHIDE_COMPILE.ii.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.nsm.o=$(RHIDE_COMPILE_NASM)
RHIDE_COMPILE.p.o=$(RHIDE_COMPILE_PASCAL)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pas.s=$(RHIDE_COMPILE.pas.s.$(PASCAL_TYPE))
RHIDE_COMPILE.pas.s.FPC=$(RHIDE_COMPILE_FPC) -a -s
RHIDE_COMPILE.pas.s.GPC=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_GPC))
RHIDE_COMPILE.pp.o=$(RHIDE_COMPILE_FPC)
RHIDE_COMPILE.s.o=$(RHIDE_COMPILE_ASM)
RHIDE_COMPILE_ADA=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  $(C_ADA_LANG_FLAGS)  $(RHIDE_OS_CFLAGS) $(CPPFLAGS)\
	$(CFLAGS) -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ARCHIVE=$(RHIDE_AR) $(RHIDE_ARFLAGS) $(OUTFILE)\
	$(ALL_OBJFILES)
RHIDE_COMPILE_ASM=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ASM_FORCE=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) -x assembler\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_C=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(RHIDE_OS_CFLAGS)  $(CPPFLAGS) $(CFLAGS) $(LOCAL_OPT) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_CC=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(RHIDE_OS_CXXFLAGS)\
	$(CPPFLAGS) $(CXXFLAGS) $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_CC_FORCE=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(RHIDE_OS_CXXFLAGS)\
	$(CPPFLAGS) $(CXXFLAGS) -x c++ $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_C_FORCE=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x c $(RHIDE_OS_CFLAGS)  $(CPPFLAGS) $(CFLAGS) $(LOCAL_OPT) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN_FORCE=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x f77 $(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FPC=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -E- $(SOURCE_NAME)
RHIDE_COMPILE_FPC_FORCE=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -B -E-\
	$(SOURCE_NAME)
RHIDE_COMPILE_GPC=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_GPC_FORCE=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) -x pascal\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_ADA=gnatbl $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(setsuffix .ali,$(OUTFILE)) $(LIBRARIES) $(LDFLAGS) \
	$(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_ADA_BIND=$(RHIDE_GNATBIND) -o $(RHIDE_ADA_BIND_FILE)\
	$(setsuffix .ali,$(OUTFILE))
RHIDE_COMPILE_LINK_ADA_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(RHIDE_ADA_BIND_FILE) $(OBJFILES) $(LIBRARIES)\
	$(LDFLAGS)  $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_DLL=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)  \
	$(RHIDE_SHARED_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_FPC=echo 'separate linking for FPK is not supported.\
	Please define a main source file in Project/Primary file.' 1>&2
RHIDE_COMPILE_LINK_FPC_AUTOMAKE=$(RHIDE_FPC) -o$(OUTFILE) $(SOURCE_NAME)\
	$(RHIDE_FPC_FLAGS) -E+
RHIDE_COMPILE_LINK_GPC=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS)\
	-o $(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(RHIDE_LDFLAGS) $(LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_GPC_AUTOMAKE=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS)  -o\
	$(OUTFILE) --automake $(RHIDE_GPC_FLAGS)  $(SOURCE_NAME)\
	$(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_PASCAL=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE))
RHIDE_COMPILE_LINK_PASCAL_AUTOMAKE=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE)_AUTOMAKE)
RHIDE_COMPILE_NASM=$(RHIDE_NASM) -f $(RHIDE_NASM_TARGET) $(LOCAL_OPT) -o\
	$(OUTFILE)  $(SOURCE_NAME)
RHIDE_COMPILE_PASCAL=$(RHIDE_COMPILE_$(PASCAL_TYPE))
RHIDE_COMPILE_PASCAL_FORCE=$(RHIDE_COMPILE_$(PASCAL_TYPE)_FORCE)
RHIDE_CONFIG_DIRS=. $(RHIDE_SHARE) $(GET_HOME)   $(RHIDE_CONFIG_DIRS_COMMON)\
	 $(addsuffix /SET,$(RHIDE_CONFIG_DIRS_COMMON))  $(SET_FILES)
RHIDE_CONFIG_DIRS_$(RHIDE_OS)=/usr/local/share/rhide /usr/share/rhide \
	/local/share/rhide /share/rhide
RHIDE_CONFIG_DIRS_COMMON=$(RHIDE_CONFIG_DIRS_$(RHIDE_OS))\
	$(RHIDE_BIN_DIR)/../share/rhide
RHIDE_CONFIG_DIRS_DJGPP=$(DJDIR)/share/rhide
RHIDE_CONFIG_DIRS_Linux=/usr/local/share/rhide /usr/share/rhide \
	/local/share/rhide /share/rhide
RHIDE_EMPTY=
RHIDE_FPC=ppc386
RHIDE_FPC_FLAGS=$(C_FPC_LANG_FLAGS) $(LOCAL_OPT) $(addprefix\
	-Up,$(INCLUDE_DIRS))  $(C_EXTRA_FLAGS)
RHIDE_FPC_LIBDIRS=$(RHIDE_FPC_LIBDIRS_$(RHIDE_OS))
RHIDE_FPC_LIBDIRS_$(RHIDE_OS)=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LIBDIRS_DJGPP=$(DJDIR)/lib
RHIDE_FPC_LIBDIRS_Linux=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LINK_FLAGS=$(RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS))
RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS)=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_DJGPP=-O coff-go32-exe $(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_Linux=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FSDB=fsdb $(OUTFILE) $(addprefix -p ,$(SRC_DIRS)) $(PROG_ARGS)
RHIDE_G77=g77
RHIDE_GCC=gcc
RHIDE_GDB=gdb $(OUTFILE) $(addprefix -d ,$(SRC_DIRS))
RHIDE_GNATBIND=gnatbind
RHIDE_GPC=gpc
RHIDE_GPC_FLAGS=$(RHIDE_INCLUDES) $(C_DEBUG_FLAGS) $(C_OPT_FLAGS)\
	$(C_WARN_FLAGS)  $(C_P_LANG_FLAGS) $(C_EXTRA_FLAGS)
RHIDE_GPROF=gprof $(OUTFILE)
RHIDE_GREP=grep -n $(prompt arguments for GREP,$(WUC) $(DEFAULT_GREP_MASK))
RHIDE_GXX=$(RHIDE_GCC)
RHIDE_INCLUDES=$(SPECIAL_CFLAGS) $(addprefix -I,$(INCLUDE_DIRS))
RHIDE_LD=$(RHIDE_GCC)
RHIDE_LDFLAGS=$(SPECIAL_LDFLAGS) $(addprefix -Xlinker ,$(LD_EXTRA_FLAGS))
RHIDE_LD_FPC=$(RHIDE_FPC) -E+
RHIDE_LD_PASCAL=gpc
RHIDE_LIBDIRS=$(addprefix -L,$(LIB_DIRS))
RHIDE_LIBS=$(addprefix -l,$(LIBS) $(RHIDE_TYPED_LIBS) $(RHIDE_OS_LIBS))
RHIDE_NASM=nasm
RHIDE_NASM_TARGET=$(RHIDE_NASM_TARGET_$(RHIDE_OS))
RHIDE_NASM_TARGET_DJGPP=coff
RHIDE_NASM_TARGET_Linux=elf
RHIDE_PATH_SEPARATOR=$(RHIDE_PATH_SEPARATOR_$(RHIDE_OS))
RHIDE_PATH_SEPARATOR_$(RHIDE_OS)=:
RHIDE_PATH_SEPARATOR_DJGPP=;
RHIDE_PATH_SEPARATOR_Linux=:
RHIDE_RLOG=$(shell rlog -R $(rlog_arg))
RHIDE_RM=rm
RHIDE_SHARED_LDFLAGS=$(RHIDE_SHARED_LDFLAGS_$(RHIDE_OS))
RHIDE_SHARED_LDFLAGS_$(RHIDE_OS)=
RHIDE_SHARED_LDFLAGS_Linux=-shared
RHIDE_SHARED_LDFLAGS_Linux=
RHIDE_SPACE=$(RHIDE_EMPTY) $(RHIDE_EMPTY)
RHIDE_STANDARD_INCLUDES=$(RHIDE_STANDARD_INCLUDES_$(RHIDE_OS))
RHIDE_STANDARD_INCLUDES_$(RHIDE_OS)=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_STANDARD_INCLUDES_DJGPP=$(addprefix $(DJDIR)/,include include/sys\
	lang/cxx lang/cxx/std)
RHIDE_STANDARD_INCLUDES_Linux=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_TYPED_LIBS=$(foreach\
	suff,$(RHIDE_TYPED_LIBS_SUFFIXES),$(RHIDE_TYPED_LIBS$(suff)))
RHIDE_TYPED_LIBS.C=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.F=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.adb=gnat
RHIDE_TYPED_LIBS.cc=$(RHIDE_TYPED_LIBS_$(RHIDE_OS).cc)
RHIDE_TYPED_LIBS.cpp=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.cxx=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.f=g2c m
RHIDE_TYPED_LIBS.for=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.fpp=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.ii=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.l=fl
RHIDE_TYPED_LIBS.m=objc
RHIDE_TYPED_LIBS.p=$(RHIDE_TYPED_LIBS_$(PASCAL_TYPE))
RHIDE_TYPED_LIBS.pas=$(RHIDE_TYPED_LIBS.p)
RHIDE_TYPED_LIBS.pp=$(RHIDE_TYPED_LIBS_FPC)
RHIDE_TYPED_LIBS_$(RHIDE_OS).cc=stdc++ m
RHIDE_TYPED_LIBS_DJGPP.cc=stdcxx m
RHIDE_TYPED_LIBS_FPC=fpc
RHIDE_TYPED_LIBS_GPC=gpc m
RHIDE_TYPED_LIBS_Linux.cc=stdc++ m
RHIDE_TYPED_LIBS_SUFFIXES=$(sort $(foreach item,$(PROJECT_ITEMS),$(suffix\
	$(item))))
_RHIDE_COMPILE_LINK_ADA=$(RHIDE_COMPILE_LINK_ADA_BIND);\
	$(RHIDE_COMPILE_LINK_ADA_LINK);   $(RHIDE_RM)\
	$(RHIDE_ADA_BIND_FILE)
%.o: %.c
	$(RHIDE_COMPILE.c.o)
%.o: %.i
	$(RHIDE_COMPILE_C)
%.o: %.cc
	$(RHIDE_COMPILE.cc.o)
%.o: %.cpp
	$(RHIDE_COMPILE.cpp.o)
%.o: %.cxx
	$(RHIDE_COMPILE.cxx.o)
%.o: %.C
	$(RHIDE_COMPILE.C.o)
%.o: %.ii
	$(RHIDE_COMPILE_CC)
%.o: %.s
	$(RHIDE_COMPILE.s.o)
%.o: %.S
	$(RHIDE_COMPILE_ASM)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.s: %.i
	$(RHIDE_COMPILE.i.s)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
%.o: %.pas
	$(RHIDE_COMPILE.pas.o)
%.o: %.p
	$(RHIDE_COMPILE.p.o)
%.o: %.pp
	$(RHIDE_COMPILE.pp.o)
%.s: %.pas
	$(RHIDE_COMPILE.pas.s)
%.o: %.m
	$(RHIDE_COMPILE_OBJC)
%.o: %.f
	$(RHIDE_COMPILE.f.o)
%.o: %.for
	$(RHIDE_COMPILE.for.o)
%.o: %.F
	$(RHIDE_COMPILE.F.o)
%.o: %.fpp
	$(RHIDE_COMPILE.fpp.o)
%.o: %.asm
	$(RHIDE_COMPILE.asm.o)
%.o: %.nsm
	$(RHIDE_COMPILE.nsm.o)
%.o: %.adb
	$(RHIDE_COMPILE.adb.o)
%.i: %.c
	$(RHIDE_COMPILE.c.i)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.ii: %.cc
	$(RHIDE_COMPILE.cc.ii)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.ii: %.cpp
	$(RHIDE_COMPILE.cpp.ii)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.ii: %.cxx
	$(RHIDE_COMPILE.cxx.ii)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.ii: %.C
	$(RHIDE_COMPILE.C.ii)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
include rhide.env
all::
clean::
	rm -f $(CLEAN_FILES)
DEPS_0= objinf/dyncat.o objinf/fstrcmp.o objinf/gzfiles.o objinf/inf.o\
	objinf/infbase.o objinf/infdummy.o objinf/infmain.o\
	objinf/infmenu.o objinf/manview.o objinf/nhiscoll.o\
	objinf/ninfview.o objinf/ninfwind.o objinf/nmanwind.o objinf/sinf.o\
	objinf/sman.o objinf/strncpyz.o libeasyd.a librhuti.a libsettv.a
NO_LINK=
LINK_FILES=$(filter-out $(NO_LINK),$(DEPS_0))
infview.exe:: $(DEPS_0)
	$(RHIDE_COMPILE_LINK)
DEPS_1=dyncat.cc configed.h dyncat.cc dyncat.h
objinf/dyncat.o:: $(DEPS_1)
	$(RHIDE_COMPILE.cc.o)
DEPS_2=
.PHONY: easydiag.gpr.force
all:: easydiag.gpr.force
easydiag.gpr.force:
	$(MAKE) -f easydiag.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_3=fstrcmp.c
objinf/fstrcmp.o:: $(DEPS_3)
	$(RHIDE_COMPILE.c.o)
DEPS_4=gzfiles.cc ceditint.h compatlayer.h configed.h gzfiles.cc gzfiles.h\
	tv.h tv/configtv.h tv/intl.h tv/ipstream.h tv/msgbox.h\
	tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objinf/gzfiles.o:: $(DEPS_4)
	$(RHIDE_COMPILE.cc.o)
DEPS_5=inf.cc ced_coma.h ced_exte.h ceditint.h ceditor.h compatlayer.h\
	configed.h diaghelp.h dyncat.h edhists.h fileopen.h fiopeaid.h\
	inf.cc inf.h infbase.h infbaser.h infr.h setstack.h settvuti.h\
	tdiagrow.h tnocastc.h tprogrdi.h tprogres.h tv.h tv/button.h\
	tv/checkbox.h tv/cluster.h tv/cmdset.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/filedlg.h tv/findrepl.h tv/frame.h tv/group.h tv/history.h\
	tv/inputln.h tv/intl.h tv/ipstream.h tv/label.h tv/listbox.h\
	tv/lstviewr.h tv/menus.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/osclipboard.h tv/palette.h tv/parttree.h tv/point.h tv/pstream.h\
	tv/radiobtn.h tv/rect.h tv/resource.h tv/scrlbar.h tv/scroller.h\
	tv/sitem.h tv/sortcoll.h tv/sortlibo.h tv/statslin.h tv/stddlg.h\
	tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/sttctext.h tv/system.h\
	tv/tkeyext.h tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h
objinf/inf.o:: $(DEPS_5)
	$(RHIDE_COMPILE.cc.o)
DEPS_6=infbase.cc ceditint.h compatlayer.h configed.h dyncat.h gzfiles.h\
	infbase.cc infbase.h infbaser.h rhutils.h setstack.h settvuti.h\
	tnocastc.h tprogdia.h tv.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/dialogs.h tv/drawbuf.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/sortcoll.h\
	tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h tvsetuti.h
objinf/infbase.o:: $(DEPS_6)
	$(RHIDE_COMPILE.cc.o)
DEPS_7=infdummy.cc
objinf/infdummy.o:: $(DEPS_7)
	$(RHIDE_COMPILE.cc.o)
DEPS_8=infmain.cc ced_coma.h ceditint.h ceditor.h codepage.h compatlayer.h\
	configed.h easydia1.h easydiag.h inf.h infalone.h infbase.h\
	infbaser.h infmain.cc infr.h manview.h pal.h setstack.h settvuti.h\
	tnocastc.h tsbutton.h tshzgrp.h tslabel.h tslistbo.h tssortlb.h\
	tssortva.h tsvegrp.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/applictn.h tv/button.h tv/chdirdlg.h tv/cmdset.h tv/codepage.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h\
	tv/drawbuf.h tv/editors.h tv/event.h tv/filedlg.h tv/fpbase.h\
	tv/fpstream.h tv/gkey.h tv/group.h tv/intl.h tv/iopstrm.h\
	tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h tv/menus.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/palette.h tv/parttree.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/screen.h\
	tv/scrlbar.h tv/scroller.h tv/sortcoll.h tv/sortlibo.h\
	tv/statslin.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
objinf/infmain.o:: $(DEPS_8)
	$(RHIDE_COMPILE.cc.o)
DEPS_9=infmenu.cc ced_coma.h ceditor.h compatlayer.h inf.h infalone.h\
	infbase.h infbaser.h infr.h setstack.h settvuti.h tnocastc.h tv.h\
	tv/app.h tv/applictn.h tv/cmdset.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/editors.h\
	tv/event.h tv/filedlg.h tv/group.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/menubar.h tv/menuitem.h tv/menus.h\
	tv/menuview.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/palette.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/scroller.h tv/sortcoll.h tv/statsdef.h tv/statsitm.h\
	tv/statslin.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/submenu.h\
	tv/system.h tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h
objinf/infmenu.o:: $(DEPS_9)
	$(RHIDE_COMPILE.cc.o)
DEPS_10=
.PHONY: librhuti.gpr.force
all:: librhuti.gpr.force
librhuti.gpr.force:
	$(MAKE) -f librhuti.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_11=manview.cc ced_coma.h ceditor.h cl/unistd.h codepage.h\
	compatlayer.h diaghelp.h dyncat.h easydia1.h easydiag.h manview.h\
	rhutils.h settvuti.h tsbutton.h tsinplin.h tslabel.h tsvegrp.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/button.h tv/codepage.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/frame.h tv/group.h tv/history.h tv/inputln.h\
	tv/intl.h tv/ipstream.h tv/label.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h tv/osclipboard.h\
	tv/palette.h tv/parttree.h tv/point.h tv/pstream.h tv/rect.h\
	tv/screen.h tv/scrlbar.h tv/scroller.h tv/stddlg.h tv/streambl.h\
	tv/sttctext.h tv/system.h tv/tkeyext.h tv/tkeys.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
objinf/manview.o:: $(DEPS_11)
	$(RHIDE_COMPILE.cc.o)
DEPS_12=nhiscoll.cc compatlayer.h settvuti.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objinf/nhiscoll.o:: $(DEPS_12)
	$(RHIDE_COMPILE.cc.o)
DEPS_13=ninfview.cc compatlayer.h settvuti.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objinf/ninfview.o:: $(DEPS_13)
	$(RHIDE_COMPILE.cc.o)
DEPS_14=ninfwind.cc compatlayer.h settvuti.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objinf/ninfwind.o:: $(DEPS_14)
	$(RHIDE_COMPILE.cc.o)
DEPS_15=nmanwind.cc compatlayer.h settvuti.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objinf/nmanwind.o:: $(DEPS_15)
	$(RHIDE_COMPILE.cc.o)
DEPS_16=
.PHONY: settv.gpr.force
all:: settv.gpr.force
settv.gpr.force:
	$(MAKE) -f settv.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_17=sinf.cc compatlayer.h inf.h infbase.h infbaser.h infr.h setstack.h\
	settvuti.h tnocastc.h tv.h tv/collectn.h tv/configtv.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/scroller.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
objinf/sinf.o:: $(DEPS_17)
	$(RHIDE_COMPILE.cc.o)
DEPS_18=sman.cc compatlayer.h manview.h tv.h tv/configtv.h tv/drawbuf.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/rect.h tv/scroller.h tv/stddlg.h tv/streambl.h tv/strmblcl.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
objinf/sman.o:: $(DEPS_18)
	$(RHIDE_COMPILE.cc.o)
DEPS_19=strncpyz.cc
objinf/strncpyz.o:: $(DEPS_19)
	$(RHIDE_COMPILE.cc.o)
all:: infview.exe
