# This file is automatically generated by RHIDE 1.5
# created with the command:
# gpr2mak libset.gpr
vpath_src=../mainsrc ../calcu ../names ../streams ../sdg ../setedit ../settvuti ../infview ../infview/names ../infview/streams
vpath %.c $(vpath_src)
vpath %.cc $(vpath_src)
vpath %.cpp $(vpath_src)
vpath %.C $(vpath_src)
vpath %.cxx $(vpath_src)
vpath %.s $(vpath_src)
vpath %.S $(vpath_src)
vpath %.p $(vpath_src)
vpath %.pas $(vpath_src)
vpath %.f $(vpath_src)
vpath %.for $(vpath_src)
vpath %.F $(vpath_src)
vpath %.fpp $(vpath_src)
vpath %.i $(vpath_src)
vpath %.ii $(vpath_src)
vpath %.m $(vpath_src)
vpath %.asm $(vpath_src)
vpath %.nsm $(vpath_src)
vpath_header=$(TVISION_INC) ../include ../settvuti/include\
	../setedit/include ../calcu ../extra ../easydiag ../sdg/include\
	../librhuti $(SUPPORT_INC) ../infview/include
vpath %.h $(vpath_header)
vpath %.hpp $(vpath_header)
vpath %.ha $(vpath_header)
vpath %.hd $(vpath_header)
vpath_obj=objlib
vpath %.o $(vpath_obj)
FLAGS_FOR_SUBPROJECTS=RHIDE_OS_="$(RHIDE_OS_)" CFLAGS="$(CFLAGS)"\
	CXXFLAGS="$(CXXFLAGS)" LDFLAGS="$(LDFLAGS)" CPPFLAGS="$(CPPFLAGS)"
RHIDE_OS=$(RHIDE_OS_)
ifeq ($(strip $(RHIDE_OS)),)
ifneq ($(strip $(DJDIR)),)
RHIDE_OS_:=DJGPP
else
RHIDE_OS_:=$(patsubst CYGWIN%,CYGWIN,$(shell uname))
endif
endif

INCLUDE_DIRS=$(TVISION_INC) ../include ../settvuti/include\
	../setedit/include ../calcu ../extra ../easydiag ../sdg/include\
	../librhuti $(SUPPORT_INC) ../infview/include
LIB_DIRS=
C_DEBUG_FLAGS=
C_OPT_FLAGS=
C_WARN_FLAGS=
C_C_LANG_FLAGS=
C_CXX_LANG_FLAGS=
C_P_LANG_FLAGS=
C_FPC_LANG_FLAGS=
C_F_LANG_FLAGS=
C_ADA_LANG_FLAGS=
LIBS=
LD_EXTRA_FLAGS=
C_EXTRA_FLAGS=-DFOR_LIBSET
LOCAL_OPT=$(subst ___~~~___, ,$(subst $(notdir $<)___,,$(filter $(notdir\
	$<)___%,$(LOCAL_OPTIONS))))

OBJFILES=objlib/bufun.o objlib/calcu.o objlib/ceditor.o objlib/completi.o\
	objlib/deedidia.o objlib/doedidia.o objlib/edconst.o\
	objlib/editorfo.o objlib/editwind.o objlib/edkeys.o\
	objlib/edprint.o objlib/edspecs.o obj/djmdr.o obj/dyncat.o\
	obj/memmove.o obj/mixer.o obj/mixersb.o obj/mixoss.o obj/stackdbg.o\
	obj/strncpyz.o obj/strndup.o objlib/gzfiles.o objlib/inf.o\
	objlib/infbase.o objlib/keytrans.o objlib/linelen.o\
	objlib/loaddefl.o objlib/loadfunc.o objlib/loadshl.o\
	objlib/loadusew.o objlib/macrocom.o objlib/mli.o objlib/mliasimp.o\
	objlib/mlicsdg.o objlib/mliediti.o objlib/mliedito.o\
	objlib/mlisdg.o objlib/nceditor.o objlib/neditwin.o\
	objlib/nfileedi.o objlib/nhiscoll.o objlib/ninfview.o\
	objlib/ninfwind.o objlib/nostatex.o objlib/nsindica.o\
	objlib/parser.o objlib/pathtool.o objlib/pclipper.o\
	objlib/pmacros.o objlib/pperl.o objlib/pphp.o objlib/ppython.o\
	objlib/pvarious.o objlib/pvhdl.o objlib/rhideint.o\
	objlib/sceditor.o objlib/sdginter.o objlib/search.o objlib/sinf.o\
	objlib/slpinter.o objlib/splinman.o objlib/ssindica.o\
	objlib/tsindica.o objlib/txhgen.o
ALL_OBJFILES=objlib/bufun.o objlib/calcu.o objlib/ceditor.o\
	objlib/completi.o objlib/deedidia.o objlib/doedidia.o\
	obj/lablchek.o obj/lablradi.o obj/snostate.o obj/tcheck2.o\
	obj/tmiclust.o obj/tsbutton.o obj/tschkarr.o obj/tschkbox.o\
	obj/tshscrol.o obj/tshzgrp.o obj/tsinplin.o obj/tsinplpi.o\
	obj/tslabel.o obj/tslider.o obj/tslistbo.o obj/tsradbot.o\
	obj/tssortlb.o obj/tssosslb.o obj/tstatext.o obj/tstextsc.o\
	obj/tstsorlb.o obj/tsvegrp.o obj/tsview.o obj/tsviewco.o\
	obj/ttextscr.o objlib/edconst.o objlib/editorfo.o objlib/editwind.o\
	objlib/edkeys.o objlib/edprint.o objlib/edspecs.o obj/djmdr.o\
	obj/dyncat.o obj/memmove.o obj/mixer.o obj/mixersb.o obj/mixoss.o\
	obj/stackdbg.o obj/strncpyz.o obj/strndup.o objlib/gzfiles.o\
	objlib/inf.o objlib/infbase.o objlib/keytrans.o objlib/linelen.o\
	objlib/loaddefl.o objlib/loadfunc.o objlib/loadshl.o\
	objlib/loadusew.o objlib/macrocom.o objlib/mli.o objlib/mliasimp.o\
	objlib/mlicsdg.o objlib/mliediti.o objlib/mliedito.o\
	objlib/mlisdg.o objlib/nceditor.o objlib/neditwin.o\
	objlib/nfileedi.o objlib/nhiscoll.o objlib/ninfview.o\
	objlib/ninfwind.o objlib/nostatex.o objlib/nsindica.o\
	objlib/parser.o objlib/pathtool.o objlib/pclipper.o\
	objlib/pmacros.o objlib/pperl.o objlib/pphp.o objlib/ppython.o\
	objlib/pvarious.o objlib/pvhdl.o objlib/rhideint.o\
	objlib/sceditor.o objlib/sdginter.o objlib/search.o obj/diaghelp.o\
	obj/dktclock.o obj/fileopen.o obj/fiopeaid.o obj/inputsca.o\
	obj/ninputsc.o obj/nostatex.o obj/nprogbar.o obj/nprogres.o\
	obj/ntnocast.o obj/ntnosost.o obj/setstack.o obj/sprogbar.o\
	obj/sprogres.o obj/stnocast.o obj/stnonost.o obj/tdiagaid.o\
	obj/tdiagrow.o obj/tinppipe.o obj/tnocastc.o obj/tnosostr.o\
	obj/tprogbar.o obj/tprogdia.o obj/tprogrdi.o obj/tprogres.o\
	obj/tstrlbox.o obj/uisarray.o obj/ussarray.o obj/viewplus.o\
	objlib/sinf.o objlib/slpinter.o objlib/splinman.o objlib/ssindica.o\
	objlib/tsindica.o objlib/txhgen.o
LIBRARIES=libeasyd.a libsettv.a
SOURCE_NAME=$<
OUTFILE=$@
SPECIAL_CFLAGS=
SPECIAL_LDFLAGS=
PROG_ARGS=
SRC_DIRS=../mainsrc ../calcu ../names ../streams ../sdg ../setedit\
	../settvuti ../infview ../infview/names ../infview/streams
WUC=
EDITORS=
MAIN_TARGET=libset.a
PROJECT_ITEMS=bufun.cc calcu.cc ceditor.cc completi.cc deedidia.cc\
	doedidia.cc easydiag.gpr edconst.cc editorfo.cc editwind.cc\
	edkeys.cc edprint.cc edspecs.cc extra.gpr gzfiles.cc inf.cc\
	infbase.cc keytrans.cc linelen.cc loaddefl.cc loadfunc.cc\
	loadshl.cc loadusew.cc macrocom.cc mli.cc mliasimp.cc mlicsdg.cc\
	mliediti.cc mliedito.cc mlisdg.cc nceditor.cc neditwin.cc\
	nfileedi.cc nhiscoll.cc ninfview.cc ninfwind.cc nostatex.cc\
	nsindica.cc parser.c pathtool.cc pclipper.cc pmacros.cc pperl.cc\
	pphp.cc ppython.cc pvarious.cc pvhdl.cc rhideint.cc sceditor.cc\
	sdginter.cc search.cc settv.gpr sinf.cc slpinter.cc splinman.cc\
	ssindica.cc tsindica.cc txhgen.cc
DEFAULT_MASK=*.cc
RHIDE_BIN_DIR=/usr/bin
PASCAL_TYPE=GPC
GET_HOME=$(HOME)
CLEAN_FILES=$(MAIN_TARGET) $(OBJFILES)
DEFAULT_GREP_MASK=*.[cfhmnps]*
RHIDE_ADA_BIND_FILE=$(addprefix _,$(setsuffix .c,$(OUTFILE)))
RHIDE_AR=ar
RHIDE_ARFLAGS=rcs
RHIDE_AS=$(RHIDE_GCC)
RHIDE_CO=$(shell co -q $(co_arg))
RHIDE_COMPILE.C.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.C.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.C.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.F.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.adb.o=$(RHIDE_COMPILE_ADA)
RHIDE_COMPILE.asm.o=$(RHIDE_COMPILE.nsm.o)
RHIDE_COMPILE.c.i=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.c.o=$(RHIDE_COMPILE_C)
RHIDE_COMPILE.c.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.cc.ii=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cc.o=$(RHIDE_COMPILE_CC)
RHIDE_COMPILE.cc.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cpp.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cpp.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cpp.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.cxx.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cxx.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cxx.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.f.o=$(RHIDE_COMPILE_FORTRAN)
RHIDE_COMPILE.for.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.fpp.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.i.s=$(RHIDE_COMPILE.c.s)
RHIDE_COMPILE.ii.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.nsm.o=$(RHIDE_COMPILE_NASM)
RHIDE_COMPILE.p.o=$(RHIDE_COMPILE_PASCAL)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pas.s=$(RHIDE_COMPILE.pas.s.$(PASCAL_TYPE))
RHIDE_COMPILE.pas.s.FPC=$(RHIDE_COMPILE_FPC) -a -s
RHIDE_COMPILE.pas.s.GPC=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_GPC))
RHIDE_COMPILE.pp.o=$(RHIDE_COMPILE_FPC)
RHIDE_COMPILE.s.o=$(RHIDE_COMPILE_ASM)
RHIDE_COMPILE_ADA=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  $(C_ADA_LANG_FLAGS)  $(RHIDE_OS_CFLAGS) $(CPPFLAGS)\
	$(CFLAGS) -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ARCHIVE=$(RHIDE_AR) $(RHIDE_ARFLAGS) $(OUTFILE)\
	$(ALL_OBJFILES)
RHIDE_COMPILE_ASM=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ASM_FORCE=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) -x assembler\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_C=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(RHIDE_OS_CFLAGS)  $(CPPFLAGS) $(CFLAGS) $(LOCAL_OPT) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_CC=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(RHIDE_OS_CXXFLAGS)\
	$(CPPFLAGS) $(CXXFLAGS) $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_CC_FORCE=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(RHIDE_OS_CXXFLAGS)\
	$(CPPFLAGS) $(CXXFLAGS) -x c++ $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_C_FORCE=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x c $(RHIDE_OS_CFLAGS)  $(CPPFLAGS) $(CFLAGS) $(LOCAL_OPT) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN_FORCE=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x f77 $(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FPC=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -E- $(SOURCE_NAME)
RHIDE_COMPILE_FPC_FORCE=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -B -E-\
	$(SOURCE_NAME)
RHIDE_COMPILE_GPC=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_GPC_FORCE=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) -x pascal\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_ADA=gnatbl $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(setsuffix .ali,$(OUTFILE)) $(LIBRARIES) $(LDFLAGS) \
	$(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_ADA_BIND=$(RHIDE_GNATBIND) -o $(RHIDE_ADA_BIND_FILE)\
	$(setsuffix .ali,$(OUTFILE))
RHIDE_COMPILE_LINK_ADA_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(RHIDE_ADA_BIND_FILE) $(OBJFILES) $(LIBRARIES)\
	$(LDFLAGS)  $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_DLL=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)  \
	$(RHIDE_SHARED_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_FPC=echo 'separate linking for FPK is not supported.\
	Please define a main source file in Project/Primary file.' 1>&2
RHIDE_COMPILE_LINK_FPC_AUTOMAKE=$(RHIDE_FPC) -o$(OUTFILE) $(SOURCE_NAME)\
	$(RHIDE_FPC_FLAGS) -E+
RHIDE_COMPILE_LINK_GPC=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS)\
	-o $(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(RHIDE_LDFLAGS) $(LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_GPC_AUTOMAKE=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS)  -o\
	$(OUTFILE) --automake $(RHIDE_GPC_FLAGS)  $(SOURCE_NAME)\
	$(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_PASCAL=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE))
RHIDE_COMPILE_LINK_PASCAL_AUTOMAKE=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE)_AUTOMAKE)
RHIDE_COMPILE_NASM=$(RHIDE_NASM) -f $(RHIDE_NASM_TARGET) $(LOCAL_OPT) -o\
	$(OUTFILE)  $(SOURCE_NAME)
RHIDE_COMPILE_PASCAL=$(RHIDE_COMPILE_$(PASCAL_TYPE))
RHIDE_COMPILE_PASCAL_FORCE=$(RHIDE_COMPILE_$(PASCAL_TYPE)_FORCE)
RHIDE_CONFIG_DIRS=. $(RHIDE_SHARE) $(GET_HOME)   $(RHIDE_CONFIG_DIRS_COMMON)\
	 $(addsuffix /SET,$(RHIDE_CONFIG_DIRS_COMMON))  $(SET_FILES)
RHIDE_CONFIG_DIRS_$(RHIDE_OS)=/usr/local/share/rhide /usr/share/rhide \
	/local/share/rhide /share/rhide
RHIDE_CONFIG_DIRS_COMMON=$(RHIDE_CONFIG_DIRS_$(RHIDE_OS))\
	$(RHIDE_BIN_DIR)/../share/rhide
RHIDE_CONFIG_DIRS_DJGPP=$(DJDIR)/share/rhide
RHIDE_CONFIG_DIRS_Linux=/usr/local/share/rhide /usr/share/rhide \
	/local/share/rhide /share/rhide
RHIDE_EMPTY=
RHIDE_FPC=ppc386
RHIDE_FPC_FLAGS=$(C_FPC_LANG_FLAGS) $(LOCAL_OPT) $(addprefix\
	-Up,$(INCLUDE_DIRS))  $(C_EXTRA_FLAGS)
RHIDE_FPC_LIBDIRS=$(RHIDE_FPC_LIBDIRS_$(RHIDE_OS))
RHIDE_FPC_LIBDIRS_$(RHIDE_OS)=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LIBDIRS_DJGPP=$(DJDIR)/lib
RHIDE_FPC_LIBDIRS_Linux=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LINK_FLAGS=$(RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS))
RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS)=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_DJGPP=-O coff-go32-exe $(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_Linux=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FSDB=fsdb $(OUTFILE) $(addprefix -p ,$(SRC_DIRS)) $(PROG_ARGS)
RHIDE_G77=g77
RHIDE_GCC=gcc
RHIDE_GDB=gdb $(OUTFILE) $(addprefix -d ,$(SRC_DIRS))
RHIDE_GNATBIND=gnatbind
RHIDE_GPC=gpc
RHIDE_GPC_FLAGS=$(RHIDE_INCLUDES) $(C_DEBUG_FLAGS) $(C_OPT_FLAGS)\
	$(C_WARN_FLAGS)  $(C_P_LANG_FLAGS) $(C_EXTRA_FLAGS)
RHIDE_GPROF=gprof $(OUTFILE)
RHIDE_GREP=grep -n $(prompt arguments for GREP,$(WUC) $(DEFAULT_GREP_MASK))
RHIDE_GXX=$(RHIDE_GCC)
RHIDE_INCLUDES=$(SPECIAL_CFLAGS) $(addprefix -I,$(INCLUDE_DIRS))
RHIDE_LD=$(RHIDE_GCC)
RHIDE_LDFLAGS=$(SPECIAL_LDFLAGS) $(addprefix -Xlinker ,$(LD_EXTRA_FLAGS))
RHIDE_LD_FPC=$(RHIDE_FPC) -E+
RHIDE_LD_PASCAL=gpc
RHIDE_LIBDIRS=$(addprefix -L,$(LIB_DIRS))
RHIDE_LIBS=$(addprefix -l,$(LIBS) $(RHIDE_TYPED_LIBS) $(RHIDE_OS_LIBS))
RHIDE_NASM=nasm
RHIDE_NASM_TARGET=$(RHIDE_NASM_TARGET_$(RHIDE_OS))
RHIDE_NASM_TARGET_DJGPP=coff
RHIDE_NASM_TARGET_Linux=elf
RHIDE_PATH_SEPARATOR=$(RHIDE_PATH_SEPARATOR_$(RHIDE_OS))
RHIDE_PATH_SEPARATOR_$(RHIDE_OS)=:
RHIDE_PATH_SEPARATOR_DJGPP=;
RHIDE_PATH_SEPARATOR_Linux=:
RHIDE_RLOG=$(shell rlog -R $(rlog_arg))
RHIDE_RM=rm
RHIDE_SHARED_LDFLAGS=$(RHIDE_SHARED_LDFLAGS_$(RHIDE_OS))
RHIDE_SHARED_LDFLAGS_$(RHIDE_OS)=
RHIDE_SHARED_LDFLAGS_Linux=-shared
RHIDE_SHARED_LDFLAGS_Linux=
RHIDE_SPACE=$(RHIDE_EMPTY) $(RHIDE_EMPTY)
RHIDE_STANDARD_INCLUDES=$(RHIDE_STANDARD_INCLUDES_$(RHIDE_OS))
RHIDE_STANDARD_INCLUDES_$(RHIDE_OS)=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_STANDARD_INCLUDES_DJGPP=$(addprefix $(DJDIR)/,include include/sys\
	lang/cxx lang/cxx/std)
RHIDE_STANDARD_INCLUDES_Linux=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_TYPED_LIBS=$(foreach\
	suff,$(RHIDE_TYPED_LIBS_SUFFIXES),$(RHIDE_TYPED_LIBS$(suff)))
RHIDE_TYPED_LIBS.C=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.F=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.adb=gnat
RHIDE_TYPED_LIBS.cc=$(RHIDE_TYPED_LIBS_$(RHIDE_OS).cc)
RHIDE_TYPED_LIBS.cpp=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.cxx=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.f=g2c m
RHIDE_TYPED_LIBS.for=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.fpp=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.ii=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.l=fl
RHIDE_TYPED_LIBS.m=objc
RHIDE_TYPED_LIBS.p=$(RHIDE_TYPED_LIBS_$(PASCAL_TYPE))
RHIDE_TYPED_LIBS.pas=$(RHIDE_TYPED_LIBS.p)
RHIDE_TYPED_LIBS.pp=$(RHIDE_TYPED_LIBS_FPC)
RHIDE_TYPED_LIBS_$(RHIDE_OS).cc=stdc++ m
RHIDE_TYPED_LIBS_DJGPP.cc=stdcxx m
RHIDE_TYPED_LIBS_FPC=fpc
RHIDE_TYPED_LIBS_GPC=gpc m
RHIDE_TYPED_LIBS_Linux.cc=stdc++ m
RHIDE_TYPED_LIBS_SUFFIXES=$(sort $(foreach item,$(PROJECT_ITEMS),$(suffix\
	$(item))))
_RHIDE_COMPILE_LINK_ADA=$(RHIDE_COMPILE_LINK_ADA_BIND);\
	$(RHIDE_COMPILE_LINK_ADA_LINK);   $(RHIDE_RM)\
	$(RHIDE_ADA_BIND_FILE)
%.o: %.c
	$(RHIDE_COMPILE.c.o)
%.o: %.i
	$(RHIDE_COMPILE_C)
%.o: %.cc
	$(RHIDE_COMPILE.cc.o)
%.o: %.cpp
	$(RHIDE_COMPILE.cpp.o)
%.o: %.cxx
	$(RHIDE_COMPILE.cxx.o)
%.o: %.C
	$(RHIDE_COMPILE.C.o)
%.o: %.ii
	$(RHIDE_COMPILE_CC)
%.o: %.s
	$(RHIDE_COMPILE.s.o)
%.o: %.S
	$(RHIDE_COMPILE_ASM)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.s: %.i
	$(RHIDE_COMPILE.i.s)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
%.o: %.pas
	$(RHIDE_COMPILE.pas.o)
%.o: %.p
	$(RHIDE_COMPILE.p.o)
%.o: %.pp
	$(RHIDE_COMPILE.pp.o)
%.s: %.pas
	$(RHIDE_COMPILE.pas.s)
%.o: %.m
	$(RHIDE_COMPILE_OBJC)
%.o: %.f
	$(RHIDE_COMPILE.f.o)
%.o: %.for
	$(RHIDE_COMPILE.for.o)
%.o: %.F
	$(RHIDE_COMPILE.F.o)
%.o: %.fpp
	$(RHIDE_COMPILE.fpp.o)
%.o: %.asm
	$(RHIDE_COMPILE.asm.o)
%.o: %.nsm
	$(RHIDE_COMPILE.nsm.o)
%.o: %.adb
	$(RHIDE_COMPILE.adb.o)
%.i: %.c
	$(RHIDE_COMPILE.c.i)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.ii: %.cc
	$(RHIDE_COMPILE.cc.ii)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.ii: %.cpp
	$(RHIDE_COMPILE.cpp.ii)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.ii: %.cxx
	$(RHIDE_COMPILE.cxx.ii)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.ii: %.C
	$(RHIDE_COMPILE.C.ii)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
include rhide.env
all::
clean::
	rm -f $(CLEAN_FILES)
DEPS_0= objlib/bufun.o objlib/calcu.o objlib/ceditor.o objlib/completi.o\
	objlib/deedidia.o objlib/doedidia.o objlib/edconst.o\
	objlib/editorfo.o objlib/editwind.o objlib/edkeys.o\
	objlib/edprint.o objlib/edspecs.o obj/djmdr.o obj/dyncat.o\
	obj/memmove.o obj/mixer.o obj/mixersb.o obj/mixoss.o obj/stackdbg.o\
	obj/strncpyz.o obj/strndup.o objlib/gzfiles.o objlib/inf.o\
	objlib/infbase.o objlib/keytrans.o objlib/linelen.o\
	objlib/loaddefl.o objlib/loadfunc.o objlib/loadshl.o\
	objlib/loadusew.o objlib/macrocom.o objlib/mli.o objlib/mliasimp.o\
	objlib/mlicsdg.o objlib/mliediti.o objlib/mliedito.o\
	objlib/mlisdg.o objlib/nceditor.o objlib/neditwin.o\
	objlib/nfileedi.o objlib/nhiscoll.o objlib/ninfview.o\
	objlib/ninfwind.o objlib/nostatex.o objlib/nsindica.o\
	objlib/parser.o objlib/pathtool.o objlib/pclipper.o\
	objlib/pmacros.o objlib/pperl.o objlib/pphp.o objlib/ppython.o\
	objlib/pvarious.o objlib/pvhdl.o objlib/rhideint.o\
	objlib/sceditor.o objlib/sdginter.o objlib/search.o objlib/sinf.o\
	objlib/slpinter.o objlib/splinman.o objlib/ssindica.o\
	objlib/tsindica.o objlib/txhgen.o libeasyd.a libsettv.a
NO_LINK=
LINK_FILES=$(filter-out $(NO_LINK),$(DEPS_0))
libset.a:: $(DEPS_0)
	$(RHIDE_COMPILE_ARCHIVE)
DEPS_1=bufun.cc bufun.h ced_coma.h ced_exte.h ceditint.h ceditor.h\
	compatlayer.h configed.h easydia1.h easydiag.h edmsg.h setapp.h\
	setstack.h settvuti.h splinman.h tdiagrow.h tnocastc.h tsbutton.h\
	tshzgrp.h tslabel.h tslistbo.h tssortva.h tssosslb.h tstatext.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/applictn.h tv/button.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/parttree.h tv/point.h tv/program.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h
objlib/bufun.o:: $(DEPS_1)
	$(RHIDE_COMPILE.cc.o)
DEPS_2=calcu.cc calcu.h ced_clas.h ced_exte.h ceditint.h ceditor.h\
	compatlayer.h configed.h edhists.h editcoma.h pmcoll.h sarray.h\
	setapp.h setstack.h settvuti.h sindicat.h tinppipe.h tnocastc.h\
	tstringa.h tv.h tv/app.h tv/applictn.h tv/button.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/group.h tv/history.h tv/indicato.h tv/inputln.h\
	tv/intl.h tv/ipstream.h tv/label.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/program.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
objlib/calcu.o:: $(DEPS_2)
	$(RHIDE_COMPILE.cc.o)
DEPS_3=ceditor.cc advice.h bufun.h ced_clas.h ced_coma.h ced_exte.h\
	ced_inte.h ceditint.h ceditor.h cl/unistd.h compatlayer.h\
	configed.h dyncat.h edhists.h gzfiles.h keytrans.h loadkbin.h\
	loadshl.h pathtool.h pmcoll.h rhutils.h sarray.h setconst.h\
	setstack.h settvuti.h sindicat.h slpinter.h tnocastc.h tprogdia.h\
	tstringa.h tstrlbox.h tv.h tv/app.h tv/cmdset.h tv/codepage.h\
	tv/collectn.h tv/colorsel.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/filedlg.h tv/findrepl.h\
	tv/gkey.h tv/group.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/lstviewr.h tv/menubox.h tv/menuitem.h tv/menus.h tv/menuview.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/osclipboard.h tv/palette.h\
	tv/parttree.h tv/point.h tv/program.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/screen.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strmblcl.h tv/strncoll.h tv/submenu.h tv/system.h\
	tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
objlib/ceditor.o:: $(DEPS_3)
	$(RHIDE_COMPILE.cc.o)
DEPS_4=completi.cc ced_clas.h ced_exte.h ced_inte.h ceditor.h compatlayer.h\
	completi.h pmcoll.h sarray.h setstack.h settvuti.h sindicat.h\
	tnocastc.h tstringa.h tv.h tv/app.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/listbox.h tv/lstviewr.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/palette.h tv/point.h tv/program.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tkeys.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/completi.o:: $(DEPS_4)
	$(RHIDE_COMPILE.cc.o)
DEPS_5=deedidia.cc ced_clas.h ced_coma.h ced_exte.h ced_inte.h ceditint.h\
	ceditor.h compatlayer.h configed.h diaghelp.h easydia1.h easydiag.h\
	edhists.h editcoma.h pmcoll.h sarray.h setapp.h setconst.h\
	setstack.h settvuti.h sindicat.h tinppipe.h tnocastc.h tsbutton.h\
	tschkbox.h tshzgrp.h tsinplin.h tsinplpi.h tslabel.h tslistbo.h\
	tsradbot.h tssortlb.h tssortva.h tstatext.h tstringa.h tstrlbox.h\
	tstsorlb.h tsvegrp.h tsview.h tsviewco.h tv.h tv/app.h\
	tv/applictn.h tv/button.h tv/checkbox.h tv/cluster.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h\
	tv/event.h tv/fpbase.h tv/fpstream.h tv/group.h tv/history.h\
	tv/indicato.h tv/inputln.h tv/intl.h tv/iopstrm.h tv/ipstream.h\
	tv/label.h tv/listbox.h tv/lstviewr.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/program.h tv/pstream.h tv/radiobtn.h tv/rect.h\
	tv/resource.h tv/scrlbar.h tv/sitem.h tv/sortcoll.h tv/sortlibo.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h\
	tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
objlib/deedidia.o:: $(DEPS_5)
	$(RHIDE_COMPILE.cc.o)
DEPS_6=doedidia.cc bufun.h ced_coma.h ced_exte.h ceditint.h ceditor.h\
	compatlayer.h configed.h edhists.h fileopen.h fiopeaid.h setconst.h\
	setstack.h settvuti.h tnocastc.h tv.h tv/app.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/drawbuf.h tv/event.h tv/fpbase.h\
	tv/fpstream.h tv/group.h tv/intl.h tv/iopstrm.h tv/ipstream.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/program.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h
objlib/doedidia.o:: $(DEPS_6)
	$(RHIDE_COMPILE.cc.o)
DEPS_7=
.PHONY: easydiag.gpr.force
all:: easydiag.gpr.force
easydiag.gpr.force:
	$(MAKE) -f easydiag.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_8=edconst.cc ced_coma.h ced_inte.h ceditor.h compatlayer.h editcoma.h\
	inf.h infbase.h infbaser.h infr.h setapp.h setstack.h settvuti.h\
	tinppipe.h tnocastc.h tv.h tv/collectn.h tv/configtv.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/msgbox.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/scroller.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
objlib/edconst.o:: $(DEPS_8)
	$(RHIDE_COMPILE.cc.o)
DEPS_9=editorfo.cc ced_clas.h ced_exte.h ced_inte.h ceditint.h ceditor.h\
	compatlayer.h configed.h pmcoll.h sarray.h setstack.h settvuti.h\
	sindicat.h tnocastc.h tstringa.h tv.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/drawbuf.h tv/event.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/parttree.h tv/point.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
objlib/editorfo.o:: $(DEPS_9)
	$(RHIDE_COMPILE.cc.o)
DEPS_10=editwind.cc ced_clas.h ced_coma.h ced_exte.h ceditint.h ceditor.h\
	compatlayer.h configed.h pmcoll.h sarray.h setstack.h settvuti.h\
	sindicat.h tnocastc.h tstringa.h tv.h tv/collectn.h tv/configtv.h\
	tv/drawbuf.h tv/event.h tv/frame.h tv/group.h tv/indicato.h\
	tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/palette.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/screen.h tv/scrlbar.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h viewplus.h
objlib/editwind.o:: $(DEPS_10)
	$(RHIDE_COMPILE.cc.o)
DEPS_11=edkeys.cc ced_coma.h ced_inte.h ceditint.h ceditor.h compatlayer.h\
	configed.h diaghelp.h dyncat.h easydia1.h easydiag.h edhists.h\
	editcoma.h edmsg.h inputsca.h keytrans.h loadkbin.h mli.h\
	mlieditd.h setapp.h setstack.h settvuti.h tdiagaid.h tdiagrow.h\
	tnocastc.h tsbutton.h tslabel.h tstatext.h tstringa.h tstrlbox.h\
	tsview.h tsviewco.h tv.h tv/app.h tv/button.h tv/cluster.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/filedlg.h tv/gkey.h\
	tv/group.h tv/intl.h tv/ipstream.h tv/label.h tv/listbox.h\
	tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/parttree.h tv/point.h\
	tv/program.h tv/pstream.h tv/radiobtn.h tv/rect.h tv/resource.h\
	tv/scrlbar.h tv/sitem.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h tv/tkeyext.h\
	tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
objlib/edkeys.o:: $(DEPS_11)
	$(RHIDE_COMPILE.cc.o)
DEPS_12=edprint.cc ceditint.h cl/unistd.h compatlayer.h configed.h\
	easydia1.h easydiag.h edmsg.h setapp.h tsbutton.h tschkbox.h\
	tshzgrp.h tsinplin.h tslabel.h tsradbot.h tsview.h tsviewco.h tv.h\
	tv/app.h tv/button.h tv/checkbox.h tv/cluster.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/fpbase.h tv/fpstream.h tv/group.h tv/history.h tv/inputln.h\
	tv/intl.h tv/iopstrm.h tv/ipstream.h tv/label.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/radiobtn.h tv/rect.h tv/sitem.h\
	tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/window.h tv/yes_mss.h
objlib/edprint.o:: $(DEPS_12)
	$(RHIDE_COMPILE.cc.o)
DEPS_13=edspecs.cc ced_inte.h compatlayer.h edspecs.h pathtool.h tv.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h tv/pstream.h\
	tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvutil.h tv/views.h
objlib/edspecs.o:: $(DEPS_13)
	$(RHIDE_COMPILE.cc.o)
DEPS_14=
.PHONY: extra.gpr.force
all:: extra.gpr.force
extra.gpr.force:
	$(MAKE) -f extra.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_15=gzfiles.cc ceditint.h cl/unistd.h compatlayer.h configed.h\
	gzfiles.h tv.h tv/configtv.h tv/intl.h tv/ipstream.h tv/msgbox.h\
	tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objlib/gzfiles.o:: $(DEPS_15)
	$(RHIDE_COMPILE.cc.o)
DEPS_16=inf.cc ced_coma.h ced_exte.h ceditint.h ceditor.h compatlayer.h\
	configed.h diaghelp.h dyncat.h edhists.h fileopen.h fiopeaid.h\
	inf.h infbase.h infbaser.h infr.h setstack.h settvuti.h tdiagrow.h\
	tnocastc.h tprogrdi.h tprogres.h tv.h tv/button.h tv/checkbox.h\
	tv/cluster.h tv/cmdset.h tv/codepage.h tv/collectn.h tv/configtv.h\
	tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h tv/filedlg.h\
	tv/findrepl.h tv/frame.h tv/group.h tv/history.h tv/inputln.h\
	tv/intl.h tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h\
	tv/menus.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/osclipboard.h\
	tv/palette.h tv/parttree.h tv/point.h tv/pstream.h tv/radiobtn.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/scroller.h tv/sitem.h\
	tv/sortcoll.h tv/sortlibo.h tv/statslin.h tv/stddlg.h tv/streambl.h\
	tv/strmblcl.h tv/strncoll.h tv/sttctext.h tv/system.h tv/tkeyext.h\
	tv/tkeys.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
objlib/inf.o:: $(DEPS_16)
	$(RHIDE_COMPILE.cc.o)
DEPS_17=infbase.cc ceditint.h cl/unistd.h compatlayer.h configed.h dyncat.h\
	gzfiles.h infbase.h infbaser.h rhutils.h setstack.h settvuti.h\
	tnocastc.h tprogdia.h tv.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/dialogs.h tv/drawbuf.h tv/intl.h tv/ipstream.h\
	tv/listbox.h tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/sortcoll.h\
	tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h tvsetuti.h
objlib/infbase.o:: $(DEPS_17)
	$(RHIDE_COMPILE.cc.o)
DEPS_18=keytrans.cc ced_coma.h ced_exte.h ceditor.h compatlayer.h dyncat.h\
	keytrans.h setstack.h settvuti.h tnocastc.h tstringa.h tv.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/event.h tv/gkey.h\
	tv/intl.h tv/ipstream.h tv/msgbox.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/pstream.h tv/resource.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tkeyext.h tv/tkeys.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/views.h tv/yes_mss.h
objlib/keytrans.o:: $(DEPS_18)
	$(RHIDE_COMPILE.cc.o)
DEPS_19=linelen.cc ced_clas.h ceditor.h compatlayer.h settvuti.h tv.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h tv/pstream.h\
	tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvutil.h tv/views.h
objlib/linelen.o:: $(DEPS_19)
	$(RHIDE_COMPILE.cc.o)
DEPS_20=loaddefl.cc ced_clas.h ced_exte.h ced_inte.h ceditor.h\
	compatlayer.h easydia1.h easydiag.h loadshl.h pathtool.h pmcoll.h\
	sarray.h setapp.h setstack.h settvuti.h sindicat.h tdiagaid.h\
	tdiagrow.h tnocastc.h tsbutton.h tshzgrp.h tsinplin.h tslabel.h\
	tslistbo.h tssortlb.h tssortva.h tstringa.h tstrlbox.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/button.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/history.h tv/indicato.h tv/inputln.h tv/intl.h\
	tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/loaddefl.o:: $(DEPS_20)
	$(RHIDE_COMPILE.cc.o)
DEPS_21=loadfunc.cc compatlayer.h pathtool.h tv.h tv/codepage.h\
	tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h tv/parttree.h\
	tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvutil.h tv/views.h
objlib/loadfunc.o:: $(DEPS_21)
	$(RHIDE_COMPILE.cc.o)
DEPS_22=loadshl.cc ced_clas.h ced_exte.h ced_inte.h ceditint.h ceditor.h\
	compatlayer.h configed.h dyncat.h loadshl.h pmcoll.h sarray.h\
	setstack.h settvuti.h sindicat.h tnocastc.h tstringa.h tv.h\
	tv/codepage.h tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/parttree.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/loadshl.o:: $(DEPS_22)
	$(RHIDE_COMPILE.cc.o)
DEPS_23=loadusew.cc ced_clas.h ced_exte.h ced_inte.h ceditor.h\
	compatlayer.h easydia1.h easydiag.h loadshl.h pathtool.h pmcoll.h\
	sarray.h setapp.h setstack.h settvuti.h sindicat.h tdiagaid.h\
	tdiagrow.h tnocastc.h tsbutton.h tshzgrp.h tsinplin.h tslabel.h\
	tslistbo.h tssortlb.h tssortva.h tstringa.h tstrlbox.h tsview.h\
	tsviewco.h tv.h tv/app.h tv/button.h tv/collectn.h tv/configtv.h\
	tv/desktop.h tv/dialog.h tv/dialogs.h tv/drawbuf.h tv/event.h\
	tv/group.h tv/history.h tv/indicato.h tv/inputln.h tv/intl.h\
	tv/ipstream.h tv/label.h tv/listbox.h tv/lstviewr.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/point.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/sortcoll.h tv/sortlibo.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/sttctext.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h tv/window.h\
	tv/yes_mss.h tvsetuti.h viewplus.h
objlib/loadusew.o:: $(DEPS_23)
	$(RHIDE_COMPILE.cc.o)
DEPS_24=macrocom.cc ced_clas.h ced_exte.h ceditor.h compatlayer.h pmcoll.h\
	sarray.h setapp.h setstack.h settvuti.h sindicat.h slpinter.h\
	tnocastc.h tstringa.h tv.h tv/app.h tv/applictn.h tv/collectn.h\
	tv/configtv.h tv/desktop.h tv/drawbuf.h tv/event.h tv/group.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/program.h tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/macrocom.o:: $(DEPS_24)
	$(RHIDE_COMPILE.cc.o)
DEPS_25=mli.cc compatlayer.h dyncat.h mli.h mliabase.h mliasimp.h mlibase.h\
	mlivar.h pathtool.h tv.h tv/codepage.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/opstream.h tv/parttree.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/views.h tv/yes_mss.h
objlib/mli.o:: $(DEPS_25)
	$(RHIDE_COMPILE.cc.o)
DEPS_26=mliasimp.cc mli.h mliabase.h mliasimp.h mlivar.h
objlib/mliasimp.o:: $(DEPS_26)
	$(RHIDE_COMPILE.cc.o)
DEPS_27=mlicsdg.cc compatlayer.h mli.h mliabase.h mlibase.h mlicsdg.h\
	mlisdg.h mlisdgi.h mlivar.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h\
	tv/yes_mss.h ucdefs.h
objlib/mlicsdg.o:: $(DEPS_27)
	$(RHIDE_COMPILE.cc.o)
DEPS_28=mliediti.cc compatlayer.h edmsg.h mli.h mliabase.h mliasimp.h\
	mlibase.h mlieditd.h mliedito.h mlivar.h settvuti.h tnocastc.h tv.h\
	tv/collectn.h tv/configtv.h tv/intl.h tv/ipstream.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/pstream.h tv/resource.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvobjs.h tv/tvutil.h tv/views.h tv/yes_mss.h tvsetuti.h
objlib/mliediti.o:: $(DEPS_28)
	$(RHIDE_COMPILE.cc.o)
DEPS_29=mliedito.cc ced_coma.h ceditor.h compatlayer.h dyncat.h edmsg.h\
	mli.h mliabase.h mlibase.h mlieditd.h mliedito.h mlisdg.h mlisdgi.h\
	mlivar.h rhutils.h runprog.h settvuti.h tnocastc.h tv.h\
	tv/collectn.h tv/configtv.h tv/intl.h tv/ipstream.h tv/msgbox.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/pstream.h tv/resource.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h tv/yes_mss.h\
	tvsetuti.h
objlib/mliedito.o:: $(DEPS_29)
	$(RHIDE_COMPILE.cc.o)
DEPS_30=mlisdg.cc compatlayer.h mli.h mliabase.h mliasimp.h mlibase.h\
	mlicsdg.h mlisdg.h mlisdgi.h mlivar.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h\
	tv/yes_mss.h
objlib/mlisdg.o:: $(DEPS_30)
	$(RHIDE_COMPILE.cc.o)
DEPS_31=nceditor.cc compatlayer.h tv/configtv.h tv/tvutil.h
objlib/nceditor.o:: $(DEPS_31)
	$(RHIDE_COMPILE.cc.o)
DEPS_32=neditwin.cc compatlayer.h tv/configtv.h tv/tvutil.h
objlib/neditwin.o:: $(DEPS_32)
	$(RHIDE_COMPILE.cc.o)
DEPS_33=nfileedi.cc compatlayer.h tv/configtv.h tv/tvutil.h
objlib/nfileedi.o:: $(DEPS_33)
	$(RHIDE_COMPILE.cc.o)
DEPS_34=nhiscoll.cc compatlayer.h settvuti.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objlib/nhiscoll.o:: $(DEPS_34)
	$(RHIDE_COMPILE.cc.o)
DEPS_35=ninfview.cc compatlayer.h settvuti.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objlib/ninfview.o:: $(DEPS_35)
	$(RHIDE_COMPILE.cc.o)
DEPS_36=ninfwind.cc compatlayer.h settvuti.h tv.h tv/configtv.h tv/intl.h\
	tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objlib/ninfwind.o:: $(DEPS_36)
	$(RHIDE_COMPILE.cc.o)
DEPS_37=nostatex.cc nostatex.h settvuti.h nostatex.cc compatlayer.h tv.h\
	tv/configtv.h tv/dialogs.h tv/drawbuf.h tv/intl.h tv/ipstream.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/stddlg.h tv/streambl.h tv/sttctext.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h
objlib/nostatex.o:: $(DEPS_37)
	$(RHIDE_COMPILE.cc.o)
DEPS_38=nsindica.cc compatlayer.h tv/configtv.h tv/tvutil.h
objlib/nsindica.o:: $(DEPS_38)
	$(RHIDE_COMPILE.cc.o)
DEPS_39=parser.c compatlayer.h tv/configtv.h
objlib/parser.o:: $(DEPS_39)
	$(RHIDE_COMPILE.c.o)
DEPS_40=pathtool.cc ceditint.h cl/unistd.h compatlayer.h configed.h\
	pathlist.h pathtool.h rhutils.h setapp.h settvuti.h tnocastc.h tv.h\
	tv/collectn.h tv/configtv.h tv/intl.h tv/ipstream.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/pstream.h tv/resource.h tv/screen.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h tv/yes_mss.h\
	tvsetuti.h
objlib/pathtool.o:: $(DEPS_40)
	$(RHIDE_COMPILE.cc.o)
DEPS_41=pclipper.cc bufun.h compatlayer.h tv.h tv/codepage.h tv/configtv.h\
	tv/intl.h tv/ipstream.h tv/opstream.h tv/parttree.h tv/pstream.h\
	tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvutil.h tv/views.h
objlib/pclipper.o:: $(DEPS_41)
	$(RHIDE_COMPILE.cc.o)
DEPS_42=pmacros.cc ceditor.h compatlayer.h pmcoll.h settvuti.h tstringa.h\
	tv.h tv/collectn.h tv/configtv.h tv/intl.h tv/ipstream.h\
	tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/pstream.h tv/resource.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h\
	tv/yes_mss.h
objlib/pmacros.o:: $(DEPS_42)
	$(RHIDE_COMPILE.cc.o)
DEPS_43=pperl.cc bufun.h
objlib/pperl.o:: $(DEPS_43)
	$(RHIDE_COMPILE.cc.o)
DEPS_44=pphp.cc bufun.h
objlib/pphp.o:: $(DEPS_44)
	$(RHIDE_COMPILE.cc.o)
DEPS_45=ppython.cc bufun.h compatlayer.h ppython.cc tv.h tv/configtv.h\
	tv/intl.h tv/ipstream.h tv/opstream.h tv/pstream.h tv/stddlg.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvutil.h\
	tv/views.h
objlib/ppython.o:: $(DEPS_45)
	$(RHIDE_COMPILE.cc.o)
DEPS_46=pvarious.cc bufun.h compatlayer.h tv.h tv/codepage.h tv/configtv.h\
	tv/intl.h tv/ipstream.h tv/opstream.h tv/parttree.h tv/pstream.h\
	tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h\
	tv/tvutil.h tv/views.h
objlib/pvarious.o:: $(DEPS_46)
	$(RHIDE_COMPILE.cc.o)
DEPS_47=pvhdl.cc bufun.h pvhdl.cc compatlayer.h tv/configtv.h
objlib/pvhdl.o:: $(DEPS_47)
	$(RHIDE_COMPILE.cc.o)
DEPS_48=rhideint.cc ced_exte.h cl/unistd.h compatlayer.h edmsg.h rhutils.h\
	tv.h tv/configtv.h tv/intl.h tv/ipstream.h tv/opstream.h\
	tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvutil.h tv/views.h
objlib/rhideint.o:: $(DEPS_48)
	$(RHIDE_COMPILE.cc.o)
DEPS_49=sceditor.cc ced_clas.h ced_exte.h ceditint.h ceditor.h\
	compatlayer.h configed.h pmcoll.h sarray.h setstack.h settvuti.h\
	sindicat.h tnocastc.h tstringa.h tv.h tv/collectn.h tv/configtv.h\
	tv/drawbuf.h tv/event.h tv/group.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h\
	tv/objects.h tv/opstream.h tv/point.h tv/pstream.h tv/rect.h\
	tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h\
	tv/strmblcl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h tv/views.h\
	tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/sceditor.o:: $(DEPS_49)
	$(RHIDE_COMPILE.cc.o)
DEPS_50=sdginter.cc ceditint.h compatlayer.h configed.h tv.h tv/configtv.h\
	tv/fpbase.h tv/fpstream.h tv/intl.h tv/iopstrm.h tv/ipstream.h\
	tv/opstream.h tv/pstream.h tv/stddlg.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvutil.h tv/views.h
objlib/sdginter.o:: $(DEPS_50)
	$(RHIDE_COMPILE.cc.o)
DEPS_51=search.cc ced_clas.h ced_exte.h ced_inte.h ceditint.h ceditor.h\
	compatlayer.h configed.h pmcoll.h sarray.h setstack.h settvuti.h\
	sindicat.h tnocastc.h tstringa.h tv.h tv/codepage.h tv/collectn.h\
	tv/configtv.h tv/drawbuf.h tv/event.h tv/indicato.h tv/intl.h\
	tv/ipstream.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/parttree.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/search.o:: $(DEPS_51)
	$(RHIDE_COMPILE.cc.o)
DEPS_52=
.PHONY: settv.gpr.force
all:: settv.gpr.force
settv.gpr.force:
	$(MAKE) -f settv.mak $(FLAGS_FOR_SUBPROJECTS)
clean::
	
DEPS_53=sinf.cc compatlayer.h inf.h infbase.h infbaser.h infr.h setstack.h\
	settvuti.h tnocastc.h tv.h tv/collectn.h tv/configtv.h tv/dialog.h\
	tv/dialogs.h tv/drawbuf.h tv/event.h tv/group.h tv/intl.h\
	tv/ipstream.h tv/listbox.h tv/lstviewr.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/scrlbar.h tv/scroller.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/window.h tv/yes_mss.h\
	tvsetuti.h
objlib/sinf.o:: $(DEPS_53)
	$(RHIDE_COMPILE.cc.o)
DEPS_54=slpinter.cc ced_clas.h ced_coma.h ced_exte.h ceditint.h ceditor.h\
	compatlayer.h completi.h configed.h easydia1.h easydiag.h edhists.h\
	edmsg.h mli.h mliabase.h mlibase.h mlieditd.h mliedito.h mlivar.h\
	pmcoll.h sarray.h setapp.h setstack.h settvuti.h sindicat.h\
	slpinter.h tinppipe.h tnocastc.h tsbutton.h tsinplpi.h tslabel.h\
	tstringa.h tsview.h tsviewco.h tv.h tv/app.h tv/button.h\
	tv/collectn.h tv/configtv.h tv/desktop.h tv/dialog.h tv/dialogs.h\
	tv/drawbuf.h tv/event.h tv/group.h tv/history.h tv/indicato.h\
	tv/inputln.h tv/intl.h tv/ipstream.h tv/label.h tv/listbox.h\
	tv/lstviewr.h tv/msgbox.h tv/no_mss.h tv/nscoll.h tv/nssorcol.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/rect.h tv/resource.h tv/scrlbar.h tv/sortcoll.h tv/sortlibo.h\
	tv/stddlg.h tv/streambl.h tv/strncoll.h tv/sttctext.h tv/system.h\
	tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h\
	tv/view.h tv/views.h tv/window.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/slpinter.o:: $(DEPS_54)
	$(RHIDE_COMPILE.cc.o)
DEPS_55=splinman.cc ced_clas.h ced_exte.h ced_inte.h ceditor.h\
	compatlayer.h pmcoll.h sarray.h setstack.h settvuti.h sindicat.h\
	splinman.h tnocastc.h tstringa.h tv.h tv/collectn.h tv/configtv.h\
	tv/drawbuf.h tv/event.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/no_mss.h tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h\
	tv/opstream.h tv/point.h tv/pstream.h tv/rect.h tv/resource.h\
	tv/scrlbar.h tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/splinman.o:: $(DEPS_55)
	$(RHIDE_COMPILE.cc.o)
DEPS_56=ssindica.cc ceditor.h compatlayer.h settvuti.h sindicat.h tv.h\
	tv/configtv.h tv/drawbuf.h tv/indicato.h tv/intl.h tv/ipstream.h\
	tv/object.h tv/objects.h tv/opstream.h tv/point.h tv/pstream.h\
	tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/system.h tv/tobjstrm.h\
	tv/ttypes.h tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/view.h\
	tv/views.h tvsetuti.h
objlib/ssindica.o:: $(DEPS_56)
	$(RHIDE_COMPILE.cc.o)
DEPS_57=tsindica.cc ced_clas.h ced_exte.h ceditor.h compatlayer.h pmcoll.h\
	sarray.h setstack.h settvuti.h sindicat.h tnocastc.h tstringa.h\
	tv.h tv/collectn.h tv/configtv.h tv/drawbuf.h tv/event.h\
	tv/indicato.h tv/intl.h tv/ipstream.h tv/no_mss.h tv/nscoll.h\
	tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h tv/point.h\
	tv/pstream.h tv/rect.h tv/resource.h tv/screen.h tv/scrlbar.h\
	tv/sortcoll.h tv/stddlg.h tv/streambl.h tv/strmblcl.h tv/strncoll.h\
	tv/system.h tv/tobjstrm.h tv/ttypes.h tv/tvconfig.h tv/tvobjs.h\
	tv/tvutil.h tv/view.h tv/views.h tv/yes_mss.h tvsetuti.h viewplus.h
objlib/tsindica.o:: $(DEPS_57)
	$(RHIDE_COMPILE.cc.o)
DEPS_58=txhgen.cc bufun.h cl/unistd.h compatlayer.h mli.h mlisdgi.h\
	rhutils.h setstack.h settvuti.h tnocastc.h tv.h tv/codepage.h\
	tv/collectn.h tv/configtv.h tv/intl.h tv/ipstream.h tv/no_mss.h\
	tv/nscoll.h tv/nssorcol.h tv/object.h tv/objects.h tv/opstream.h\
	tv/parttree.h tv/pstream.h tv/resource.h tv/sortcoll.h tv/stddlg.h\
	tv/streambl.h tv/strncoll.h tv/system.h tv/tobjstrm.h tv/ttypes.h\
	tv/tvconfig.h tv/tvobjs.h tv/tvutil.h tv/views.h tv/yes_mss.h\
	txhgen.h
objlib/txhgen.o:: $(DEPS_58)
	$(RHIDE_COMPILE.cc.o)
all:: libset.a
